### ISSUE TITLE
Quake II RTX does not launch with older Nvidia drivers since 1.4.0 

### ISSUE THREAD

**Issue by guest1984** [NVIDIA/Q2RTX#100]
Since updating to 1.4.0 game menu doesnt load. The game starts in Steam, then exists instantly.

The latest Nvidia drivers work and Vulkan is automatically set.  This update means it breaks support for older drivers (i'm on 445.87) 
possibly if they don't include the new Vulkan API. When I tested the Vulkan API there was no difference between Vulkan and the Nvidia extension in Q2 RTX
Is this a bug in the 1.4.0 update?  I reverted by drivers as the latest Nvidia drivers cause CPU latency since Reflex was implemented

Thanks

**Comment by apanteleev** [comment]
What happens when you try to run the game without Steam? Just locate the `q2rtx.exe` executable and run it. There should be some sort of error message.

**Comment by guest1984** [comment]
Hi Alexeym thanks for the quick reply.  It says the follow when launching the exe
q2rtx.exe - Entry Point Not Found

The precedure entry point vkGetBufferDeviceAddress could
not be located in the dynamic link library
D:\Games\SteamApps\common\Quake II RTX\q2rtx.exe

**Comment by apanteleev** [comment]
Thank you, that made sense.
Fixed in https://github.com/NVIDIA/Q2RTX/commit/0a16c7302d19e884a9fa6e46044cd69f74b60469

Keeping the issue open until verified on your end.

**Comment by guest1984** [comment]
No problem :)
Do I need to modify q2rtx.exe or other files somewhere as per 0a16c73?

**Comment by apanteleev** [comment]
Yes, you need a replacement q2rtx.exe, and new shaders that are compatible with it, because there have been changes in `master` since v1.4.0. Here's a package with that for you, just extract it over the existing q2rtx install.
[q2rtx-patch-0a16c730.zip](https://github.com/NVIDIA/Q2RTX/files/5735733/q2rtx-patch-0a16c730.zip)

**Comment by guest1984** [comment]
I have that a try and it launches but running RTX there is only a black screen with sound.  FPS is also around 10fps with settings I ran before (3440x1440, 2080Ti)
Same with Nvidis and Vulkan extensions.  Same with all settings lowest / off
Open GL does work
Thanks for your help with this

**Comment by apanteleev** [comment]
That's what would happen if you didn't extract the `baseq2/shaders.pkz` file from my zip attached above. Please make sure to replace that file as well as the executable.

**Comment by guest1984** [comment]
Sorted now, thanks again.  I had a shaders_backup.pkz in the baseq2 location.  Once I moved this it worked :)
Having a playthough again.  Here's a screenshot.
A fantastic classic game, brought to life with modern hardware

https://i.imgur.com/XurMUTz.jpg

**Comment by apanteleev** [comment]
Great, thanks for confirming.
Closing.
