### ISSUE TITLE
Handle 0 extents Swapchain on Windows

### ISSUE THREAD

**Issue by skarthik0196** [NVIDIA/Q2RTX#103]
```
if(surf_capabilities.currentExtent.width != ~0u) {
		qvk.extent_unscaled = surf_capabilities.currentExtent;
	}
	else {
		qvk.extent_unscaled.width = MIN(surf_capabilities.maxImageExtent.width, qvk.win_width);
		qvk.extent_unscaled.height = MIN(surf_capabilities.maxImageExtent.height, qvk.win_height);

		qvk.extent_unscaled.width = MAX(surf_capabilities.minImageExtent.width, qvk.extent_unscaled.width);
		qvk.extent_unscaled.height = MAX(surf_capabilities.minImageExtent.height, qvk.extent_unscaled.height);
	}
```

When AltTabbing out of fullscreen, if the window extents become 0, the swapchain create code will attempt to create a swapchain with 0 extents on Windows. _vkGetPhysicalDeviceSurfaceCapabilitiesKHR()_ can return 0 in min, max and current extents. As per Vulkan specification section 33.2.3 I think swapchain creation should be avoided until it changes.

```
With Win32, minImageExtent, maxImageExtent, and currentExtent must always equal the window size.
The currentExtent of a Win32 surface must have both width and height greater than 0, or both of them 0.

Due to above restrictions, it is only possible to create a new swapchain on this platform with imageExtent being equal to the current size of the window.
The window size may become (0, 0) on this platform (e.g. when the window is minimized), and so a swapchain cannot be created until the size changes.

```

Both AMD and Nvidia platforms appear to succeed swapchain creation with 0 extents, but this triggers some bad behavior in Steam Overlay that crashes AMD platforms. After 0 extent swapchain creation succeeds, steam overlay creates images with 0 extents and tries to call _vkAllocateMemory_ with a 0 _allocationSize_ and eventually tries to bind these 0 memory allocations to their resources which crashes inside the AMD driver. While SteamOverlay does cause the problem, it was still triggered by Q2RTX creating an illegal swapchain and I think it would be a good idea to handle this particular case.

**Comment by apanteleev** [comment]
Fixed in https://github.com/NVIDIA/Q2RTX/commit/5f8ec125af82c9c11060e0cead3e6c2bdf1faecd
