### ISSUE TITLE
Per-Raytrace-pass Heatmap

### ISSUE THREAD

**Issue by PMunkes** [NVIDIA/Q2RTX#106]
Hi, would it be possible to implement a heatmap to the profiler, like in this blog post?
https://developer.nvidia.com/blog/profiling-dxr-shaders-with-timer-instrumentation/
This would enable better insight into the relative cost of each part of the scene and it would be an interesting insight into the implementation of Raytracing by the different Vendors.
Ideally this would be toggle-able per Raytrace pass.

**Comment by tntljc** [comment]
Nsight Graphics has this feature available in the latest release, check the "Shader Timing Heatmap".

**Comment by PMunkes** [comment]
I don't own a Raytracing capable nVidia card, so Nsight is not an option for me.
