### ISSUE TITLE
Enable bufferDeviceAddressMultiDevice feature

### ISSUE THREAD

**Issue by AaronHaganAMD** [NVIDIA/Q2RTX#115]
https://github.com/NVIDIA/Q2RTX/blob/59d424cfcb03a2fb756981792886b2c8f172590b/src/refresh/vkpt/main.c#L1239-L1243

Can .bufferDeviceAddressMultiDevice = VK_TRUE be set here as well ?

**Comment by apanteleev** [comment]
Done.
