### ISSUE TITLE
Framerate counter odd behavior with r_maxfps

### ISSUE THREAD

**Issue by Cannonaire** [NVIDIA/Q2RTX#117]
Under certain circumstances, the framerate counter will display a completely wrong value, such as 1000 fps when the framerate is 50. This bug occurred on my old graphics card, an RTX 2060 FE, and it still occurs on my new one, a 3090 FE.

This happens under the following conditions:
cl_async is 1
r_maxfps is lower than the current framerate cap

This often occurs when you use vsync or some other framerate lmiter, such as RTSS. It also occurs when r_maxfps is set to a lower framerate value than you would otherwise be getting. It may need to be 10fps or more below cap to display the wrong value.

*EDIT* The framerate limiter with r_maxfps doesn't seem to be very accurate when compared to RTSS - setting it to 60 gives me 63 fps.

![20210427193116_1](https://user-images.githubusercontent.com/76081111/116338831-3965c700-a791-11eb-98ed-3eb6abffc9be.jpg)

**Comment by apanteleev** [comment]
Fixed by merging https://github.com/NVIDIA/Q2RTX/pull/118 
Thanks @res2k !
