### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by Nielsbishere** [NVIDIA/Q2RTX#121]
https://github.com/NVIDIA/Q2RTX/blob/master/src/refresh/vkpt/shader/asvgf_taau.comp#L89
```glsl
float t = (float(linear_idx) + 0.5) / float(preload_size.x);
int xx = int(floor(fract(t) * float(preload_size.x)));
int yy = int(floor(t));
```
Why isn't this written like
```glsl
uint xx = linearIdx % preloadSize.x;
uint yy = linearIdx / preloadSize.x;
```
Is there a specific performance reason I'm missing?

**Comment by QwazyWabbitWOS** [comment]
It appears to be avoiding a potential divide by zero error. 
Writing it the way you propose would throw an exception if preloadSize.x is 0.

**Comment by Nielsbishere** [comment]
@QwazyWabbitWOS but then your width would be zero and you shouldn't even enter the function

**Comment by apanteleev** [comment]
I'm late to reply here, but the reason is that GPUs are generally faster at floating point math than integer math, especially division. In this case, it probably doesn't matter though, because there's just one or two such operation per thread.

**Comment by Nielsbishere** [comment]
Hi, thanks for the update. Is there some documentation of how much this difference is? Is it a very noticeable difference (provided not a lot of extra instructions are introduced) or is this an optimization in terms of <15%.
