### ISSUE TITLE
Does Q2RTX have "masked" material type ?

### ISSUE THREAD

**Issue by motorsep** [NVIDIA/Q2RTX#127]
I have a texture of vines/roots with alpha channel (so in-game a brush would have one side with that texture and the rest of the sides would ne NODRAW, MIST content, so that the vines/root appear opaque while the rest of the space around is see-through).

It seems that Q2RTX can't render such setup, unlike modern Quake 1 engine forks. The face of the brush with roots/vines renders black (where transparency should be) and the sides of the brush with NODRAW also render.

Is it even possible to have such setup in Q2RTX ? If so, how? If not, could you please add support for this (as a special type perhaps) ?

Thanks

**Comment by apanteleev** [comment]
Currently the renderer does not support masked materials, but it's certainly possible to add them. That would need a few any-hit shaders to evaluate the masks.

**Comment by motorsep** [comment]
> Currently the renderer does not support masked materials, but it's certainly possible to add them. That would need a few any-hit shaders to evaluate the masks.

Great! Could you please add support for such materials ?

**Comment by motorsep** [comment]
Btw, this is what I need masked materials for (vines / roots):

![fte-20210809183217-0](https://user-images.githubusercontent.com/1927918/128787790-e0f36663-85d4-45a2-b848-2c56a0bf4d45.png)

**Comment by apanteleev** [comment]
Implemented in https://github.com/NVIDIA/Q2RTX/commit/f0be30b4109bbcab5cfd323737cd6fbf97814896

**Comment by motorsep** [comment]
Awesome! Thanks a bunch !

**Comment by motorsep** [comment]
Oh, one thing I totally forgot about - can this be a two-sided material? For example, having masked material and lighting behind it:

![image](https://user-images.githubusercontent.com/1927918/129499059-10f5f8b4-ba80-484e-9870-070634a0254b.png)

or something like this (railing, metal lattice constructions, etc.):

![image](https://user-images.githubusercontent.com/1927918/129499166-bb9b8881-717d-48b3-b16f-6f11ef8db5f3.png)

**Comment by apanteleev** [comment]
With masked materials being two-sided currently, I think this issue can be closed. @motorsep
