### ISSUE TITLE
Incorrect location on loading checkpoints

### ISSUE THREAD

**Issue by jonnypanic** [NVIDIA/Q2RTX#13]
After dying, on levels with multiple separate maps, reloading the autosave often puts you in the wrong area. This can lead either to a game-breaking bug (not being able to get past a door you haven't unlocked yet) or to skipping big sections of the level. 

I assumed this was a problem with Quake 2, not the nvidia version, but others think it is this version only that has this problem. 

More info:
https://steamcommunity.com/app/1089130/discussions/0/1636410430549717402/

**Comment by WaxxyOne** [comment]
To reproduce:

Start a new game and complete the first level. After the second map loads, turn around and hit the elevator button to return to the first map. This will create an autosave. Go to the load game menu and load the save. You will be teleported to the start of the level, but the status of everything else in the level (killed enemies, collected items) will be correctly loaded.

This bug does not affect manual saves.

**Comment by apanteleev** [comment]
This issue was inherited from Q2PRO which still behaves like that in the latest version.
Fix submitted in commit https://github.com/NVIDIA/Q2RTX/commit/c3ab9826f865e4bce50b9ccc2eebcb699e94a497
