### ISSUE TITLE
Exponential fog support

### ISSUE THREAD

**Issue by motorsep** [NVIDIA/Q2RTX#132]
Would it be possible to add support for configurable exponential colored fog (to be applied per level) ? Something like this:

![image](https://user-images.githubusercontent.com/1927918/128788683-7f14f111-51a1-4328-8ce2-2ac5ce427086.png)

![image](https://user-images.githubusercontent.com/1927918/128788746-613363f9-1083-4975-ab27-43b626eedfac.png)

**Comment by apanteleev** [comment]
After some discussions and experiments, fog is implemented: https://github.com/NVIDIA/Q2RTX/commit/23920ff8c178c4a78b2c2057afb00081082b19ad

**Comment by Rroff2** [comment]
![quake006](https://user-images.githubusercontent.com/75708770/141193323-939ec90d-65fa-49c8-b9b9-ad508567fd9f.jpg)

![quake007](https://user-images.githubusercontent.com/75708770/141193344-135cf7b3-d15e-411d-b796-14048cd58c59.jpg)

Words fail me.

**Comment by apanteleev** [comment]
> Words fail me.

In a good way? :)

**Comment by Rroff2** [comment]
> In a good way? :)

Oh definitely in a good way. A bit harder to use it to get those kind of visuals indoors but it really looks good outdoors.

**Comment by Beilerbey** [comment]
This is looking sweet, could someone please point me in the direction of good maps to download? Thanks :)
