### ISSUE TITLE
Model lighting noisy or not emissive at all

### ISSUE THREAD

**Issue by MartianDays** [NVIDIA/Q2RTX#135]
So I've noticed models emit no light when they're set to is_light 1, and their lighting is very noisy when set to the default is_light 0. I've altered some material settings to punctuate the issue:

Setting:
> is_light 0
> emissive_scale 5

![Quake 2 RTX Remaster Screenshot 2021 08 22 - 09 09 29 42](https://user-images.githubusercontent.com/15644824/130362612-b312fb57-5d49-4c20-a441-07d1935d0573.png)

Setting:
> is_light 1
> emissive_scale 5

![Quake 2 RTX Remaster Screenshot 2021 08 22 - 09 10 46 70](https://user-images.githubusercontent.com/15644824/130362623-43cd47c9-e4ac-4a02-868c-ae97c93ea99f.png)

Emitting clean light from meshes would be extremely helpful and open doors for artists to create interesting level geometry beyond BSPs! I see a lot of super-cool opportunities here.

Hope this is helpful! :)

**Comment by MartianDays** [comment]
Could be related to issue #134 ??

**Comment by apanteleev** [comment]
Support for polygonal lights in non-bsp meshes has been added in db56a0d09545582d36f32fa9d736804b73de775b.
See the commit notes for more information on current limitations.

**Comment by MartianDays** [comment]
> 
> 
> Support for polygonal lights in non-bsp meshes has been added in [db56a0d](https://github.com/NVIDIA/Q2RTX/commit/db56a0d09545582d36f32fa9d736804b73de775b).
> See the commit notes for more information on current limitations.

Amazing, thank you! Tested! Marking this as done. :D
