### ISSUE TITLE
Parallax Occlusion Map Support?

### ISSUE THREAD

**Issue by MartianDays** [NVIDIA/Q2RTX#138]
This feature adds so much potential depth and detail to environments that I would be remiss if I didn't bring it up!

Parallax Occlusion, especially seen in Star Citizen, adds a whole world of detail to their models - usually used to add final touches and greebles. In the context of Quake 2 RTX, this is especially true with all the surfaces in the game: from walls with studs and other interesting shapes otherwise made to look flat by BSPs. POM could resolve these issues and make the game really "pop", and offer artists like myself another very powerful tool to author content in this engine! It would be hugely beneficial for POM to work on both BSPs and meshes.

A couple screenshots for good measure:

Without pointing it out:
![Squadron 42 - Star Citizen Screenshot 2021 08 15 - 10 23 20 14](https://user-images.githubusercontent.com/15644824/130712989-5c5ea8d2-97ba-4e37-ba34-e42ad6b56c8b.png)

With pointing it out:
![Squadron 42 - Star Citizen Screenshot 2021 08 15 - 10 23 20 14_LI](https://user-images.githubusercontent.com/15644824/130705369-c0232a4a-db9b-4677-ba1b-b0d427029d3d.jpg)

It occurs to me also that this could also benefit from stepping / quality toggles for users to tweak performance values in-game. :)

Thanks so much for reading! If you need assets to test this with, let me know: I'm happy to put some together.

**Comment by motorsep** [comment]
I am just going to leave this link here (slide 25, silhouette POM), for a reference:
https://www.slideshare.net/TiagoAlexSousa/rendering-technologies-from-crysis-3-gdc-2013

**Comment by MartianDays** [comment]
> 
> 
> I am just going to leave this link here (slide 25, silhouette POM), for a reference:
> https://www.slideshare.net/TiagoAlexSousa/rendering-technologies-from-crysis-3-gdc-2013

Absolutely, a silhouette with POM would be ideal!

**Comment by res2k** [comment]
This was previously and briefly mentioned here: https://github.com/NVIDIA/Q2RTX/issues/40#issuecomment-515194200
