### ISSUE TITLE
Removing dead and insane soldiers with nomonsters 1

### ISSUE THREAD

**Issue by CKWarner** [NVIDIA/Q2RTX#14]
On line 622 of src/baseq2/g_spawn.c, replacing 
```C
if (nomonsters->value && strstr(ent->classname, "monster")) {
```

with
```C
if (nomonsters->value && (strstr(ent->classname, "monster") || strstr(ent->classname, "misc_deadsoldier") || strstr(ent->classname, "misc_insane"))) {
```

means that the corpses and insane soldiers are removed, along with the enemies, when using *nomonsters 1*.

I needed to do this with my own copy, and thought that it might be useful for someone else wanting to achieve the same thing.

**Comment by CKWarner** [comment]
I made a patch file for it, I think

```
622c622
< 			if (nomonsters->value && strstr(ent->classname, "monster")) {
---
> 			if (nomonsters->value && (strstr(ent->classname, "monster") || strstr(ent->classname, "misc_deadsoldier") || strstr(ent->classname, "misc_insane"))) {
```

**Comment by apanteleev** [comment]
Merged as https://github.com/NVIDIA/Q2RTX/pull/30
