### ISSUE TITLE
Support for Skeletal Animation

### ISSUE THREAD

**Issue by BlackShadow** [NVIDIA/Q2RTX#144]
Would been awesome move to add Skeletal animation to the game and share the tools with community to make our own character with skeletal system.

**Comment by motorsep** [comment]
Afaik there is IQM support in Q2RTX, which is skeletal format. 
As for tools, there is Blender/Maya/3DS MAX/Akeytsu.. Make your pick. You can either export directly into IQM using the first 3 suits or export into FBX from either of them and use Noesis to convert FBX into IQM.

**Comment by BlackShadow** [comment]
> Afaik there is IQM support in Q2RTX, which is skeletal format.
> As for tools, there is Blender/Maya/3DS MAX/Akeytsu.. Make your pick. You can either export directly into IQM using the first 3 suits or export into FBX from either of them and use Noesis to convert FBX into IQM.

Ah really? Didn't know about that! Will Google for more info. Thank you.
