### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by DadSchoorse** [NVIDIA/Q2RTX#147]
The current release and what's available on e.g. Steam does not work with RADV, which recently added an initial RT implementation.
e5f75f476102217f809fcc946163ae6d3419e5d7 is needed to start the game, because RADV only reports two queue families (general and compute). So it would be nice if there was a new release with that commit included.

**Comment by mercuriete** [comment]
I have the exact same problem:

AMD 6900XT
environmental variable
```
RADV_PERFTEST=rt
```

output:
```
FATAL: Could not find a suitable Vulkan queue family!
```

Please do a new release on steam.

**Comment by Squall-Leonhart** [comment]
This is a bug in RADV, any driver implementing vulkan should be capable of running RT on the graphics queue.

**Comment by mercuriete** [comment]
That I think is a game bug because the queue 0 is graphic, compute and Transfer.
You dont need to use diferent queues you can use the first one that fits in your pourpose.

https://vulkan.gpuinfo.org/displayreport.php?id=13143#queuefamilies

**Comment by Squall-Leonhart** [comment]
And yet QuakeRTX is doing exactly that, but RADV falls over itself.

Not the first time RADV has issues with the transfer queue either.

**Comment by DadSchoorse** [comment]
RADV doesn't have an issue with the transfer queue, RADV has no dedicated transfer queue.
That's not a radv bug, Q2RTX just makes wrong assumptions.

**Comment by Squall-Leonhart** [comment]
Then RADV is in the wrong, relearn the vulkan spec

**Comment by Joshua-Ashton** [comment]
Please feel free to point out where Vulkan demands an dedicated transfer queue.

Don't worry, we'll wait!

**Comment by PMunkes** [comment]
@Squall-Leonhart then Q2 RTX is also wrong, since they removed the transfer queue in commit e5f75f476102217f809fcc946163ae6d3419e5d7 from May.

**Comment by Squall-Leonhart** [comment]
no they didn't, learn to read source code thanks.

**Comment by PMunkes** [comment]
Devices must only support one queue family and transfer capabilities are OPTIONAL. [https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#devsandqueues-queues](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#devsandqueues-queues
)![image](https://user-images.githubusercontent.com/6448982/142781931-453b50be-d993-44c3-afa9-afd9ea6d8e1b.png)
![image](https://user-images.githubusercontent.com/6448982/142782027-21288bb8-18cb-4170-b5a2-29754826d96d.png)

**Comment by PMunkes** [comment]
@Squall-Leonhart The current HEAD works on RADV (performance is currently not great, but it works).
![image](https://user-images.githubusercontent.com/6448982/142782493-034d5f30-0100-4d75-a2d0-d6415b36f80c.png)

**Comment by PMunkes** [comment]
@Squall-Leonhart Q2RTX was initializing 3 separate queues before e5f75f47, one for compute, one for graphics and one for transfers. The proprietary drivers provided at least three separate queues (graphics+compute+transfer and compute+transfer and transfer), while RADV only provides two (graphics+compute+transfer and compute+transfer). 
Since the commit removed the dependency on a third queue (which was not required from a conformant implementation by the specification) the Compute+Transfer queue of RADV could be used for transfers.

RADV:
![image](https://user-images.githubusercontent.com/6448982/142782969-5b9a608c-d61e-4e34-a69c-23d035699238.png)
AMD proprietary:
![image](https://user-images.githubusercontent.com/6448982/142783040-6ad68275-45d9-4b28-975b-80b64e5f3e92.png)

**Comment by apanteleev** [comment]
Just letting everyone know: we heard you, and a new release should be ready sometime soon.
In the meantime, you can use the prebuilt binaries from the new CI pipeline, [here](https://github.com/NVIDIA/Q2RTX/actions)

**Comment by mercuriete** [comment]
Thanks for the release! ❤️❤️

**Comment by ChrisDeadman** [comment]
I get segmentation fault when running the new version :(
I am running RADV with latest Mesa 22.0.0-devel (git-4198ca4b3f).

```
==131663== 1 errors in context 1 of 2:
==131663== Invalid read of size 4
==131663==    at 0x2DB8FF78: ??? (in /usr/lib/libvulkan_radeon.so)
==131663==    by 0x2DB7480C: ??? (in /usr/lib/libvulkan_radeon.so)
==131663==    by 0x2DB7C523: ??? (in /usr/lib/libvulkan_radeon.so)
==131663==    by 0x2DB7C95A: ??? (in /usr/lib/libvulkan_radeon.so)
==131663==    by 0x56C9CB: vkpt_vertex_buffer_create_pipelines (in /run/media/deadman/LinuxGames/steam/steamapps/common/Quake II RTX/q2rtx)
==131663==    by 0x51ADE7: vkpt_initialize_all (in /run/media/deadman/LinuxGames/steam/steamapps/common/Quake II RTX/q2rtx)
==131663==    by 0x527EAD: R_Init_RTX (in /run/media/deadman/LinuxGames/steam/steamapps/common/Quake II RTX/q2rtx)
==131663==    by 0x4310FD: CL_InitRefresh (in /run/media/deadman/LinuxGames/steam/steamapps/common/Quake II RTX/q2rtx)
==131663==    by 0x42860B: CL_Init (in /run/media/deadman/LinuxGames/steam/steamapps/common/Quake II RTX/q2rtx)
==131663==    by 0x46C2E7: Qcommon_Init (in /run/media/deadman/LinuxGames/steam/steamapps/common/Quake II RTX/q2rtx)
==131663==    by 0x4BB5AA: main (in /run/media/deadman/LinuxGames/steam/steamapps/common/Quake II RTX/q2rtx)
==131663==  Address 0x60 is not stack'd, malloc'd or (recently) free'd
==131663== 
==131663== 
==131663== 1 errors in context 2 of 2:
==131663== Use of uninitialised value of size 8
==131663==    at 0x2DB8FF78: ??? (in /usr/lib/libvulkan_radeon.so)
==131663==    by 0x2DB7480C: ??? (in /usr/lib/libvulkan_radeon.so)
==131663==    by 0x2DB7C523: ??? (in /usr/lib/libvulkan_radeon.so)
==131663==    by 0x2DB7C95A: ??? (in /usr/lib/libvulkan_radeon.so)
==131663==    by 0x56C9CB: vkpt_vertex_buffer_create_pipelines (in /run/media/deadman/LinuxGames/steam/steamapps/common/Quake II RTX/q2rtx)
==131663==    by 0x51ADE7: vkpt_initialize_all (in /run/media/deadman/LinuxGames/steam/steamapps/common/Quake II RTX/q2rtx)
==131663==    by 0x527EAD: R_Init_RTX (in /run/media/deadman/LinuxGames/steam/steamapps/common/Quake II RTX/q2rtx)
==131663==    by 0x4310FD: CL_InitRefresh (in /run/media/deadman/LinuxGames/steam/steamapps/common/Quake II RTX/q2rtx)
==131663==    by 0x42860B: CL_Init (in /run/media/deadman/LinuxGames/steam/steamapps/common/Quake II RTX/q2rtx)
==131663==    by 0x46C2E7: Qcommon_Init (in /run/media/deadman/LinuxGames/steam/steamapps/common/Quake II RTX/q2rtx)
==131663==    by 0x4BB5AA: main (in /run/media/deadman/LinuxGames/steam/steamapps/common/Quake II RTX/q2rtx)
```
