### ISSUE TITLE
CommandLine Error: Option 'help-list' registered more than once!

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [NVIDIA/Q2RTX#148]
I am getting CommandLine Error: Option 'help-list' registered more than once! error when I launch the game.
turning rtx off fixes it, but I want to launch the game with rtx. I am using the RADV drivers on linux.

**Comment by res2k** [comment]
Googling for the message "Option 'help-list' registered more than once!" indicates that it's emitted by LLVM.
Q2RTX doesn't have a direct dependency on LLVM, so the problem originates somewhere else.
AFAIK Mesa uses LLVM, so maybe the issue is there...

**Comment by res2k** [comment]
FWIW, I recommend you try some other programs that make use of Vulkan ray tracing. (Just googling "vulkan raytracing example" gives plenty open source examples.) If you get that same message with other programs it's a strong indication that the problem is somewhere in the Vulkan implementation.

**Comment by Etaash-mathamsetty** [comment]
it seems like its more of a warning even wine is showing this error. Sorry!
