### ISSUE TITLE
Hand misalignment with weapons

### ISSUE THREAD

**Issue by CKWarner** [NVIDIA/Q2RTX#15]
![quake000](https://user-images.githubusercontent.com/49373348/59480332-245f4380-8e58-11e9-887e-2b559d978e99.png)
I'm not sure exactly when this happened; I'm pretty sure it all lined up properly at release. The game is using some kind of specific override - the hand doesn't change at all when changing player skin - which doesn't line up with the weapon.

**Comment by apanteleev** [comment]
Not sure what's wrong here. The hand and weapon models in Q2 are entirely separate from the player model/skin. If you look closely at reflections, you'll notice that the weapon is not reflected at all, and the player model doesn't really match your movement (if you have the "view" setting in Player Setup at "first person model", of course)

**Comment by CKWarner** [comment]
What's wrong is that the hand is too far into the gun, or that the gun is too far into the hand. You also have exactly the same view whether you choose "first person model" or "just the gun." Whichever model and animations you're using for the hand is misaligned with whichever model you're using for the weapons.

**Comment by apanteleev** [comment]
Oh I see. The hand and weapon are actually parts of the same model/animation file, and it comes for Q2XP. Most of these "new" weapons are not great, but they are better than the original models.
