### ISSUE TITLE
How to disable overlay text info?

### ISSUE THREAD

**Issue by zohozer** [NVIDIA/Q2RTX#152]
I want to play Quake2RTX on my Ubuntu 20.10 machine but I can't find a way to disable the text overlay that is is displayed on the screen (in the red circle). I do searched on internet for a solution but I can't find any. Please help. Thank you

![Quake2RTX_Overlay](https://user-images.githubusercontent.com/5983791/135756739-3ba9843e-a244-4bb6-8373-8d814b2d2965.png)
.

**Comment by res2k** [comment]
Look for "GPU profiler" in the settings.

**Comment by zohozer** [comment]
Thank you. It is working!
