### ISSUE TITLE
Odd framebuffer artifacts related to bloom

### ISSUE THREAD

**Issue by res2k** [NVIDIA/Q2RTX#158]
I'm lately noticed artifacts related to bloom:
![image](https://user-images.githubusercontent.com/4117506/140312726-e483f4d1-d4c4-46e9-a9c1-ff8883f53e21.png)
(The screenshot was created by hacking blur_composite to pass through from `TEX_BLOOM_VBLUR`, for better visibility. Also certain settings were tweaked to dial up the effect, see below.)

Some observations:
1. FSR (specifically, FSR EASU) exacerbates the issue. (However, it does not _trigger_ it - without it, artifacts still occur, though less frequently.)
2. When setting `viewsize` to 50 or below, the whole screen suffers these artifacts. Above that, only a fraction.
3. Some of the blocks look like `TEX_BLOOM_VBLUR` contents, but after the "downscale" step, without any blurring applied.
4. It's not visible when with a non-zero `bloom_debug` setting.
5. I found two changes that seem to work around the cause of the issue: first, downscaling to a separate texture (ie don't reuse `IMG_BLOOM_VBLUR`), second was an attempt to merge the 2nd bloom pass with compositing.

My guess is that it is some synchronization issue related to `IMG_BLOOM_VBLUR`, based on the visual appearance of the blocks, the workarounds I found (which basically avoid reusing that image) and that `bloom_debug` also doesn't exhibit the issue (notably, enabling this invokes barriers and image layout changes).

However, I'm at a loss how to "properly" fix it. I tried to sprinkle around some additional barriers, but that didn't help.
@apanteleev Do you happen to have an idea what could cause this?
Or if you don't have one either, what's your opinion of making a PR of one of the workarounds?

**Comment by res2k** [comment]
(FWIW, this occurs independently of any clock speed changes.)

**Comment by apanteleev** [comment]
This is a driver bug that's been fixed in the 496.61 hotfix release.
Download here: https://nvidia.custhelp.com/app/answers/detail/a_id/5253

**Comment by res2k** [comment]
> This is a driver bug that's been fixed in the 496.61 hotfix release. Download here: https://nvidia.custhelp.com/app/answers/detail/a_id/5253

Indeed, with that driver the issue is gone.
Thanks for the hint!
