### ISSUE TITLE
Rendering issue with new build

### ISSUE THREAD

**Issue by CKWarner** [NVIDIA/Q2RTX#16]
This is how it should look, and how it looks with the build I did a few days ago.
![quake001](https://user-images.githubusercontent.com/49373348/59555694-3c48db80-8fae-11e9-910c-c6ee763b1a94.png)

This is how it looks with the build I did today
![quake002](https://user-images.githubusercontent.com/49373348/59555706-65696c00-8fae-11e9-8050-f04f5b7dfbab.png)

and this is how it looks after changing the renderer to OpenGL and back to RTX (a vid_restart has the same effect)
![quake003](https://user-images.githubusercontent.com/49373348/59555718-7fa34a00-8fae-11e9-928a-74af4a43debd.png)

Something peculiar has happened in the last couple of days. Also note that there's some kind of graph by default.

**Comment by CKWarner** [comment]
Here's another shot from later in the game that shows the image:
![quake004](https://user-images.githubusercontent.com/49373348/59555784-b594fe00-8faf-11e9-80d9-162fecc388e6.png)
It seems to be showing a display of lit areas, or somesuch.

**Comment by CKWarner** [comment]
It has occurred to me that the old build might have been using an old (older than your listed required version) of libvulkan-dev, and this might be using the current version. Or the old one might have still been using the current version of libvulkan-dev; I can't remember exactly when I updated it.

**Comment by apanteleev** [comment]
Please try rebuilding the client, including shaders. There has been a change in the global UBO layout, and it can look all kinds of weird if the shaders' layout doesn't match the CPU side.

**Comment by CKWarner** [comment]
Those shots were taken by getting a fresh clone of the source, then doing 
```
cd Q2RTX/
mkdir build
cd build/
cmake ..
cmake --build .
```
If there's something else that I should have done as well, I'm happy to test it.

**Comment by apanteleev** [comment]
Depends on how/when you're mounting baseq2 into the game tree. The shaders are built into `baseq2/shader_vkpt`; and the packaged builds that Nvidia distributes have shaders packaged into `baseq2/shaders.pkz`. Try removing both, and then running `cmake --build .`

**Comment by CKWarner** [comment]
OK, tracked down the problem, I think. The new build didn't have a shaders.pkz, but there _was_ a shaders.pkz in ~/.quake2rtx/baseq2/ from an earlier Steam install. Removing that seems, from a cursory look, to allow it to render correctly. I'll test later to see if it's all working correctly, but it _does_ now produce the right kind of image.

**Comment by apanteleev** [comment]
That makes sense. I'm not sure how search paths work on Linux with the `~/.quake2rtx` folder, but on Windows loose files in baseq2 take precedence over pkz files. Apparently, that homedir folder is even higher priority. (I haven't worked on the Linux version at all)

**Comment by CKWarner** [comment]
Just checked the build process from the beginning. Doing 
```
git clone --recursive https://github.com/NVIDIA/Q2RTX.git
cd Q2RTX/
mkdir build
cd build/
cmake ..
cmake --build .
```
then copying blue_noise.pkz and q2rtx_media.pkz to Q2RTX/baseq/ without having any shaders.pkz anywhere seems to work properly. That could probably go in the build instructions of the Readme - they weren't ever so clear.
