### ISSUE TITLE
Health gets reset on level change.

### ISSUE THREAD

**Issue by CKWarner** [NVIDIA/Q2RTX#17]
If you leave a level with greater than your normal maximum health - because you've picked up some of the single-unit health packs, for example - your health gets reset down to the maximum health (100 + _n_ adrenalines) instead. This is obviously incorrect behaviour.

**Comment by DU-jdto** [comment]
> This is obviously incorrect behaviour.

Is it? This has been in every version of Quake 2 I've tried, and I always assumed it was intended.

**Comment by CKWarner** [comment]
> Is it? This has been in every version of Quake 2 I've tried, and I always assumed it was intended.

Hmm; you're right that the GOG version does it too. I'd not played through Quake 2 before this version.

It still seems like a mistake that's just never been corrected: you keep all your armour and items intact over level changes, after all.

**Comment by CKWarner** [comment]
It's a simple patch to change the behaviour, which I've done on my one because I think it kinda sucks.

```
461,462d460
<         if (ent->health > ent->client->pers.max_health)
<             ent->health = ent->client->pers.max_health;
```
