### ISSUE TITLE
Cvar rcon_password is erroneously saved in q2config.cfg

### ISSUE THREAD

**Issue by QwazyWabbitWOS** [NVIDIA/Q2RTX#176]
In Commit 9ae17fbe, file src/common/common.c, line 956; the flags state for rcon_password was changed from CVAR_PRIVATE to CVAR_ARCHIVE.
This is an error. Clients should never save rcon_password.
This also makes rcon_password vulnerable to macro expansion via malicious servers.

**Comment by apanteleev** [comment]
Fixed in https://github.com/NVIDIA/Q2RTX/commit/701cf318995c91486bb212114e8c8279287a5bb7 
Closing.
