### ISSUE TITLE
[Linux]  Compile Error with version 1.6.0

### ISSUE THREAD

**Issue by jrugia** [NVIDIA/Q2RTX#177]
Attempting to compile the 1.6.0 (as of commit 701cf31) release is failing with the below error:

```
/home/jojo/Q2RTX-1.6.0/src/refresh/gl/texture.c: In function ‘gl_anisotropy_changed’:
/home/jojo/Q2RTX-1.6.0/src/refresh/gl/texture.c:122:18: error: ‘GL_MAX_TEXTURE_MAX_ANISOTROPY’ undeclared (first use in this function)
     qglGetFloatv(GL_MAX_TEXTURE_MAX_ANISOTROPY, &value);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jojo/Q2RTX-1.6.0/src/refresh/gl/texture.c:122:18: note: each undeclared identifier is reported only once for each function it appears in
/home/jojo/Q2RTX-1.6.0/src/refresh/gl/main.c: In function ‘GL_Strings_f’:
/home/jojo/Q2RTX-1.6.0/src/refresh/gl/main.c:657:22: error: ‘GL_MAX_TEXTURE_MAX_ANISOTROPY’ undeclared (first use in this function)
         qglGetFloatv(GL_MAX_TEXTURE_MAX_ANISOTROPY, &value);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jojo/Q2RTX-1.6.0/src/refresh/gl/main.c:657:22: note: each undeclared identifier is reported only once for each function it appears in
/home/jojo/Q2RTX-1.6.0/src/refresh/gl/texture.c: In function ‘GL_SetFilterAndRepeat’:
/home/jojo/Q2RTX-1.6.0/src/refresh/gl/texture.c:588:45: error: ‘GL_TEXTURE_MAX_ANISOTROPY’ undeclared (first use in this function)
             qglTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MAX_ANISOTROPY, gl_filter_anisotropy);
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~
src/CMakeFiles/client.dir/build.make:2056: recipe for target 'src/CMakeFiles/client.dir/refresh/gl/main.c.o' failed
```

I looked up the GL_MAX_TEXTURE_MAX_ANISOTROPY function and apparently it's found in 'glext.h' whereas these files only include 'gl.h'. I  tried adding `#include "glext.h"` in the files but that doesn't solve the problem. Unfortunately that's as far as my knowledge goes in this regard.

**Comment by QwazyWabbitWOS** [comment]
Looks like your dependencies might be out of date.
Make sure your packages are all up to date. `sudo apt update`, `sudo apt upgrade`, etc.
Delete the `build` directory you created under the `Q2RTX-1.6.0` folder.
Create the empty build directory again.
Then reinitialize the cmake dependencies: `cmake ..` from within the `build` directory.
Once that's done, `cmake --build .` ought to build everything correctly.

**Comment by jrugia** [comment]
I went back at this issue, cloned the master repo but issue still persists. I can't pinpoint from where the issue is originating from.

- Tried newer version of GCC (10.3.0)
- Compiling against some newer headers of Mesa (21.3.7)

Still getting same error. It's probably coming from a dependency on my end but I can't figure out which from.

**Comment by res2k** [comment]
You should probably find out which `gl.h` is used in your case (or more generally, where the OpenGL-related definitions come from).

You can try this:
1. grab the command line for the file that breaks (if cmake doesn't tell you, try setting `VERBOSE=1` in the environment)
2. copy the command line & edit it to replace `-o <blah.o>` with `-E` - this will instruct gcc to "preprocess only" and makes it possible to track the included files
3. run the edited command line (with redirecting to a file), look for what `gl.h` or `GL.h` is included (or not)

This may give you a hint about where the `GL_` things come from or not.
You could also get some more info by passing `-Wp,-dM` to gcc. Also see https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html for more options, some which may be helpful to track down the issue.

**Comment by jrugia** [comment]
@res2k  Thanks for the info, will look into it.

**Comment by FabioLolix** [comment]
Building from git master on Arch Linux work without workarounds

**Comment by res2k** [comment]
> gcc -E /home/jojo/Q2RTX/src/refresh/gl/texture.c

This command looks like if it is missing all `-I...` arguments... those are "include paths", without them the compiler won't know where to look.

That's why I said "copy the command line & edit it" - the command line, as produced by cmake, will contain all the correct arguments. You _only_ need to replace `-o <blah.o>` with `-E`.

**Comment by jrugia** [comment]
@res2k  I think I got it right this time. The output was quite big.

Terminal output: [Output.txt](https://github.com/NVIDIA/Q2RTX/files/8557090/Output.txt)

**Comment by res2k** [comment]
Hmm, it's using the GL headers from `/usr/include/GL`, which is probably right...

**Comment by jrugia** [comment]
> Hmm, it's using the GL headers from `/usr/include/GL`, which is probably right...

That's what I suspected from the little I could understand from the output. I swapped them out for some newer ones and it's now compiling fine :)

I think it's also finally time to close this ticket. Thanks for your help :)
