### ISSUE TITLE
player model is overexposed from tone mapping changes

### ISSUE THREAD

**Issue by CKWarner** [NVIDIA/Q2RTX#18]
This is how it is now

![quake000](https://user-images.githubusercontent.com/49373348/59566221-f7c44b00-9054-11e9-9e7b-edd57a66dd1a.png)

and this is how it was in the initial release

![quake001](https://user-images.githubusercontent.com/49373348/59566222-fb57d200-9054-11e9-8a60-0ee4ccb98040.png)

which looks much better

**Comment by apanteleev** [comment]
Fixed in commit https://github.com/NVIDIA/Q2RTX/commit/38a7266a9cfbb0b907e8cdb942901aa9aaa91ca6

**Comment by CKWarner** [comment]
Yep, that seems to have fixed it.
