### ISSUE TITLE
Additions to the readme.

### ISSUE THREAD

**Issue by CKWarner** [NVIDIA/Q2RTX#20]
The full build instructions aren't complete, for Linux at least.

```
git clone --recursive https://github.com/NVIDIA/Q2RTX.git
cd Q2RTX/
mkdir build
cd build/
cmake ..
cmake --build .
```
are the commands you'll need. Note that it's Q2RTX, not q2rtx as it currently says in the Readme, and the `cmake ..` is not specified but is crucial.

Also, the minimum version of Ubuntu should be Ubuntu 16.04; there isn't an Ubuntu 16 - the format is year.month.

Since the media files are critical to having the game run, and they're right here on github, [linking to them](https://github.com/NVIDIA/Q2RTX/releases) should be done in the readme, and it could be made clearer that they go in Q2RTX/baseq2.

**Comment by XrizZ** [comment]
Additional hints:
- when configuring cmake files for curl, you can ignore the warning "Found no *nroff program". This is about man pages and are not mandatory for quake.

**Comment by apanteleev** [comment]
Changes made in commit https://github.com/NVIDIA/Q2RTX/commit/18b6aaeeacb78f04362698d0e61ed0702c46bd1e

Good enough?

**Comment by CKWarner** [comment]
I think so. Thanks.
