### ISSUE TITLE
Heartbeat to multiple master servers

### ISSUE THREAD

**Issue by RoLex** [NVIDIA/Q2RTX#204]
Hi.

I'm currently having an issue sending heartbeats to other master servers than ``master.q2servers.com`` using Q2RTX 1.6.0 dedicated server.

I'm setting up my server including following configs:

```
setmaster master.q2servers.com master.quakeservers.net q2master.planetquake.com netdome.biz
set public 1
```

Upon starting the server I see following:

```
Master server at 142.4.216.103:27900.
Master server at 78.47.113.68:27900.
Master server at 165.160.15.20:27900.
Master server at 5.9.88.215:27900.
```

Upon using ``listmasters`` command I get following:

```
num hostname              lastmsg address
--- --------------------- ------- ---------------------
  1 master.q2servers.com     3395 142.4.216.103:27900
  2 master.quakeservers.n   never 78.47.113.68:27900
  3 q2master.planetquake.   never 165.160.15.20:27900
  4 netdome.biz             never 5.9.88.215:27900
```

``master.q2servers.com`` is the only one that keeps increasing last message, other ones are always ``never``.

I have even tried to change the order of servers in ``setmaster`` and restarting server, still only ``master.q2servers.com`` is being pinged, regardless of its position on row 1 through 4.

Regards.

**Comment by res2k** [comment]
Hi,
could you do that same test with Q2PRO?
This will help in narrowing the issue.

**Comment by RoLex** [comment]
@res2k

Yes, exactly the same issue:

```
num hostname              lastmsg address
--- --------------------- ------- ---------------------
  1 master.q2servers.com     3492 142.4.216.103:27900
  2 master.quakeservers.n   never 78.47.113.68:27900
  3 q2master.planetquake.   never 165.160.15.20:27900
  4 netdome.biz             never 5.9.88.215:27900
```

Using:

```
====== Q2PRO initialized ======
q2proded r1910~8b8d647, Feb 17 2022
https://github.com/skullernet/q2pro
```

Regards.

**Comment by RoLex** [comment]
In fact I should have tested each one of the master servers before posting this as an issue. It seems that other 3 master servers are not sending ``ack`` in reply to ``heartbeat`` request, therefore no status to dedicated server.

My server doesn't receive anything at all from ``165.160.15.20`` and ``5.9.88.215``, so probably those are dead. While ``78.47.113.68`` is only sending ``status 23`` to my server, which is incorrect requests, atleast for server vs pinger protocol.

So both Q2Pro and Q2RTX are working correctly with heartbeats. False alarm, sorry. It's good to have these stuff documented anyway since it is very hard to find any kind of information on Quake 2 these days, most resources are dead and has been removed from Google indexing.

Regards.
