### ISSUE TITLE
Health Reset Between Torture Chambers and Security Complex

### ISSUE THREAD

**Issue by BoostAddicted** [NVIDIA/Q2RTX#206]
I noticed that leaving the Security Complex and entering The Torture Chambers (or vice versa) resets health if you happen to have more health than your max + adrenaline you've picked up.  Example: say you pick up a few +1 health stimpacks and have 112 health, but your max health plus adrenaline picked up is 107.  Entering or leaving between these two maps seems to reset my health back to 107.

**Comment by Paril** [comment]
This is a known bug in Quake II. Your health is capped to your max_health when you load a new level; you lose any additional mega health/stimpack health you've picked up.
