### ISSUE TITLE
Cloudy While Under Water

### ISSUE THREAD

**Issue by BoostAddicted** [NVIDIA/Q2RTX#207]
I noticed that with the latest v1.6.0 release being underwater is quite cloudy making it hard to navigate/see the environment.  I'm not sure if this is intentional, but it is quite hard to see.  I did some searching on this topic and could not find that someone had mentioned this change from v1.5.0.  I did not experience this with the previous v1.5.0.

**Comment by Beilerbey** [comment]
I noticed it too, I think it has to do with the implementation of fog but don't quote me on that as I'm far from an expert.

**Comment by apanteleev** [comment]
I think you're talking about the "blend" effects that use the original game's fullscreen overlay color for item pickups and being underwater. Try disabling that with `tm_blend_enable 0` from console.

**Comment by res2k** [comment]
There are also a couple of other `tm_blend_scale_XXX` cvars which can be used to tweak the appearance that effect.

**Comment by Beilerbey** [comment]
Yes, that does it, thanks a lot.

**Comment by BoostAddicted** [comment]
> I think you're talking about the "blend" effects that use the original game's fullscreen overlay color for item pickups and being underwater. Try disabling that with `tm_blend_enable 0` from console.

That did the trick.  I don't recall changing anything with my settings when moving from 1.5 > 1.6.  Did something change between the versions to alter the blend effects?

**Comment by res2k** [comment]
1.5.0 did not have that blend effect at all, support for it was added in 1.6.0.

**Comment by apanteleev** [comment]
I've adjusted the FS blend effects in https://github.com/NVIDIA/Q2RTX/commit/3b927ebf6d276d162d1f61091b67cb9496e9ac7d

Closing
