### ISSUE TITLE
Q2RTX still uses Xwayland on Wayland

### ISSUE THREAD

**Issue by xcom169** [NVIDIA/Q2RTX#217]
Hello All!

I found that with the latest version 1.6.0 of Q2RTX still uses XWayland (X.Org) even if I use 100% Wayland session. 
I use Manjaro Linux with Gnome GUI and AMD Vega 56 GPU. 

If I force SDL_VIDEODRIVER=wayland then the game crashes on the startup. 

Is it possible to run the game without XWayland ?

Thanks!

**Comment by res2k** [comment]
Could you give the Linux artifact from here: https://github.com/NVIDIA/Q2RTX/actions/runs/2286315995 a try?

**Comment by xcom169** [comment]
Hello!
It works, but 
RTX mode is not working  (Couldn't initialize textures)
It seems the graphics quality is lower than in XWayland mode.  (Is it possible? )

**Comment by res2k** [comment]
What do you mean with "couldn't initialize textures"?
That shouldn't have changed... Did you extract all the files from the archive or just the binary?

Graphics quality shouldn't be lower _per se_. Perhaps darker due to dcd28504cd3b122e77962ae2152e41a8858d4f84.
Do you have screenshots for comparison?

**Comment by xcom169** [comment]
Yes, the whole dir. 

Screens: 
![image](https://user-images.githubusercontent.com/17802090/167398418-a08d9773-cfb2-4c8a-93e1-0cd20febc71d.png)

![image](https://user-images.githubusercontent.com/17802090/167398590-fd29a86a-6215-4ed9-8403-07f560f072c7.png)

![image](https://user-images.githubusercontent.com/17802090/167398954-2a243f63-fb84-4149-9fa7-ef57d5c6047f.png)

**Comment by res2k** [comment]
Here's a new build that should print more error details to the console: https://github.com/NVIDIA/Q2RTX/runs/6350916803
Once that completed it may give some more insights.

But does RTX mode work with X11 mode?
If not then it's probably a limitation of your graphics hardware and/or driver.

**Comment by xcom169** [comment]
No, not even in " SDL_VIDEODRIVER=x11 ./q2rtx "  mode RTX is working.  
With the stock 1.6 version from Steam it's working with X11. 

I got an error message on my console. Maybe it's connected: 
error loading blue noise tex blue_noise/256_256/HDR_RGBA_0000.png

**Comment by res2k** [comment]
> I got an error message on my console. Maybe it's connected:
> error loading blue noise tex blue_noise/256_256/HDR_RGBA_0000.png

Weird. That file is contained in `baseq2/blue_noise.pkz`, which in turn is shipped with Q2RTX.
Is that file there?

**Comment by xcom169** [comment]
I'll check. I just need some time to get to my PC again

**Comment by xcom169** [comment]
Hello!  This file was missing from the build zip, but I manually copied them there. 
Now also RTX mode is working! 
Thanks, I think this ticket can be closed.

**Comment by Calinou** [comment]
@apanteleev Looks like this issue can be closed now :slightly_smiling_face:

**Comment by SpidFightFR** [comment]
Okay so, i found out that you can build the game specifically for wayland, by running in the root of the repo: `cmake -D SDL_X11=OFF -D SDL_WAYLAND=ON -B build`.

This will (as it says) disable support for X11 sdl videodriver and enable wayland support, thus avoiding to be forced to run `SDL_VIDEODRIVER=wayland` environment variable while running the game.

The thing is that the baseq2 folder misses files at the end, so you'll need to copy/paste the baseq2 folder from a prebuilt version of Q2RTX.

After this it indeed [works without Xwayland](https://i.imgur.com/tbGfdrV.png). 
Tho the Game seem to be **VERY** [dark](https://i.imgur.com/rHXvBnq.jpg) in RTX mode, idk what's causing this...

**Comment by xcom169** [comment]
Thanks a lot! It's closed.

**Comment by res2k** [comment]
> Tho the Game seem to be **VERY** [dark](https://i.imgur.com/rHXvBnq.jpg) in RTX mode, idk what's causing this...

Could be a color space issue. 
IIRC Q2RTX produces color values in the sRGB color space.
If the color values are interpreted as "linear" values, but a linear-to-sRGB conversion is applied for displaying, it will look too dark.
(See https://en.wikipedia.org/wiki/SRGB for conversion formulas.)

**Comment by SpidFightFR** [comment]
> > Tho the Game seem to be **VERY** [dark](https://i.imgur.com/rHXvBnq.jpg) in RTX mode, idk what's causing this...
> 
> Could be a color space issue. IIRC Q2RTX produces color values in the sRGB color space. If the color values are interpreted as "linear" values, but a linear-to-sRGB conversion is applied for displaying, it will look too dark. (See https://en.wikipedia.org/wiki/SRGB for conversion formulas.)

Okay, so how can i fix this issue? I have to modify the game files?

**Comment by res2k** [comment]
> Okay, so how can i fix this issue? I have to modify the game files?

Ideally, this would be something addressed by the graphics stack (adding support for sRGB surface formats).
I suppose it'd be also possible to address this in Q2RTX, however, that's more work with quite possibly inferior output quality (compared to a "native" solution).
