### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Arlandrian** [NVIDIA/Q2RTX#22]
using vs2019
Im getting compilation error while building.

Q2RTX/src/refresh/vkpt/shader/asvgf_lf.comp:156: 'format' : image formats must match

I followed the build instructions, what could this be?

**Comment by aaronp24** [comment]
I had a similar problem on Arch Linux after it upgraded the glslang package to version 7.11.3214-1. Downgrading it to 7.11.3188-1 fixed it for me.

**Comment by Arlandrian** [comment]
I downgraded VulkanSDK  from version 1.1.108.0 to 1.1.97.0 and the problem is fixed. But now .pak files are missing where can i find them?
