### ISSUE TITLE
NaN issue

### ISSUE THREAD

**Issue by DU-jdto** [NVIDIA/Q2RTX#23]
Due to floating point fun, when NoV is calculated on line 539 of direct_lighting.rgen it can very rarely come out very slightly greater than 1. When this happens, it can cause a NaN result in the following computations. Under most circumstances Q2RTX quickly recovers from this error, but when the reference path tracing mode is active the affected pixel turns black and remains black forever.

In my local fork, I've fixed this by replacing the NoV computation with:

`float NoV = clamp(-dot(normal, direction), 0, 1);`

**Comment by apanteleev** [comment]
Fixed in commit https://github.com/NVIDIA/Q2RTX/commit/2891a024325e39955c5c8e3ed6c24e4e912f5e26
Thank you!
