### ISSUE TITLE
FSR Bug?

### ISSUE THREAD

**Issue by ForbiddenEra** [NVIDIA/Q2RTX#230]
Hello!

So I wrote up this huge post because I had been capped at 75fps and it seemed to only be affecting Q2; tried a *ton* of different things over a *while* and was final-checking some things before posting an issue and found "Max Frame Rate" set to 74FPS in "Manage 3D Settings" in NVIDIA control panel which I think mostly only affects ogl/vulkan..d'oh!

Anyway; during this escapade, I noticed an issue with 1.6:

I also maybe found a bug with FSR and scaling:
![image](https://user-images.githubusercontent.com/7980490/171085574-61387154-362b-40cc-94fe-83ad2d228915.png)
![image](https://user-images.githubusercontent.com/7980490/171085619-c2c6cf3e-3eeb-4faa-879e-a5702088bcaf.png)

This is with dynamic scaling on and maximum scaling at 75% and then 50%; it doesn't seem to happen with fixed scaling however.

Cheers!

**Comment by LaurenceGough** [comment]
I am getting the same issue in Quake II RTX with FSR enabled. Nvidia driver ver 511.79 (later ones give terrible stutters).

**Comment by ForbiddenEra** [comment]
Nice to see fixed; thanks!

Will try when I see the next release!
