### ISSUE TITLE
Noisy image at low resolutions

### ISSUE THREAD

**Issue by Adriaaaaan** [NVIDIA/Q2RTX#233]
When lowering the resolution I expected the amount of noise to go down as more of the frame time could be spent doing more accumulation.   Is this possible?  I'd expect that running this at 640x480 on an rtx 3090 would produce a clean image?  Would be nice if it could automatically accumulate for as long as possible rather than a set number.  It would allow for better IQ depending on the hardware

**Comment by apanteleev** [comment]
Multi-sampled rendering is not supported the way you describe it (although possible). You can simulate it by supersampling, i.e. setting `viewsize 200` or more.
