### ISSUE TITLE
Support for Lossless FLAC/WAVE (CD Tracks)

### ISSUE THREAD

**Issue by MartyShepard** [NVIDIA/Q2RTX#24]
Quake 2 has a Famous Soundtrack all in time. Please add FLAC/WAVE Support for Lossless. Personally, i dont like OGG/MP3.

**Comment by josestefan** [comment]
Most users agree OGG achieves transparency at -q 5. A lot of software uses OGG internally, and you'd likely never know about it because the information may not be exposed.

-q 5.0 is only halfway to the maximum setting of "10.0". If you can spot the difference between a good encode and lossless, I invite you to post the results of a proper ABX test. And then try to spot the difference while having all the other sound effects added on top.

**Comment by Marat-Tanalin** [comment]
Original “Quake II” had **lossless CD-Audio music**.

“Quake II RTX” currently only supports Ogg Vorbis which is **lossy**. Lossy music is **degradation** compared with the original game.

Support for a lossless audio format such as FLAC or Wave would restore the ability to enjoy the **original CD-quality music**.

Compared with Wave (`*.wav`), the FLAC (`*.flac`) format allows to save about **35% of drive space** in case of “Quake II”. **Both** Wave and FLAC are **lossless**, FLAC just uses **archiver-like** compression.

Other open-source “Quake II” versions that support lossless music:

* [vkQuake2](https://github.com/kondrak/vkQuake2) (FLAC, Wave)
* [Quake2xp](https://sourceforge.net/p/quake2xp/code/HEAD/tree/) (Wave)
* [Q2DOS](https://bitbucket.org/neozeed/q2dos/src/master/) (Wave)

The corresponding code could probably be adapted from one of them just like the Ogg-Vorbis code was adapted from yquake2.

It also probably makes sense to fix the typo in the issue title by replacing the wrong los**E**less with the correct los**S**less that would allow others to easier find this issue.

@josestefan
> Most users agree OGG achieves transparency at -q 5.

Theoretical “transparency” of a lossy format doesn’t matter once you know for sure it’s lossy. Storytelling about transparency is irrelevant unhelpful noise.

**Comment by MartyShepard** [comment]
ouch.. Yes, i mean Los**s**less.

**Comment by Marat-Tanalin** [comment]
@MartyShepard Has it been implemented?
