### ISSUE TITLE
Add PhysX Flow support

### ISSUE THREAD

**Issue by Adriaaaaan** [NVIDIA/Q2RTX#245]
Physics flow is now open source!  Can we now restore the cut fluid dynamics?  https://github.com/NVIDIA-Omniverse/PhysX/tree/release/104.0/flow

**Comment by apanteleev** [comment]
The rendering part of Flow is not open source, only the editor.

**Comment by Calinou** [comment]
[Flow is now open source under 3-clause BSD](https://github.com/NVIDIA-Omniverse/PhysX/discussions/384). Does this mean it's within the realm of possibility now?

**Comment by Adriaaaaan** [comment]
Ha that was my first thought when I saw this.  It won't happen but it would
have been amazing to see this project run with latest tech

**Comment by res2k** [comment]
> **Edit:** [Probably not for now](https://github.com/NVIDIA-Omniverse/PhysX/discussions/384#discussioncomment-12730220), as it would need a Vulkan backend.

There's some Vulkan stuff here: https://github.com/NVIDIA-Omniverse/PhysX/tree/fb8aebeecd0e52f2484f1e5c06aa00a98325fa51/flow/source/nvflowext/vulkan
Maybe that's sufficient? Didn't look into it to deep.
