### ISSUE TITLE
Uninitialized pNext Pointer

### ISSUE THREAD

**Issue by andrew-lunarg** [NVIDIA/Q2RTX#247]
```cpp
        VkDeviceGroupDeviceCreateInfo device_group_create_info;
	VkPhysicalDeviceGroupProperties device_group_info; // <------- Struct is not zeroed.

	if(num_device_groups > 0) {
		// we always use the first group
		num_device_groups = 1;
		_VK(vkEnumeratePhysicalDeviceGroups(qvk.instance, &num_device_groups, &device_group_info)); // <---- Whether pNext is zero is undefined. It might often accidentally be so.
```
`src/refresh/vkpt/main.c`

In the example above, `VkPhysicalDeviceGroupProperties device_group_info {};` would zero out the `pNext` pointer.

The `sType` is also not set in this example.

Might be worth doing a sweep of the code for similar cases.

Here is a Godbolt snippet showing struct members not being zeroed by default: https://godbolt.org/z/K8n7Wsj4h

**Comment by apanteleev** [comment]
Thanks for reporting the issue.

This has been fixed by https://github.com/NVIDIA/Q2RTX/pull/246
