### ISSUE TITLE
Indirect lighting

### ISSUE THREAD

**Issue by DU-jdto** [NVIDIA/Q2RTX#25]
A few things in indirect_lighting.rgen.

1. The condition on line 104 as with other SH-related things should probably include an `&& global_ubo.flt_enable != 0`.

2. When low_freq is updated at lines 299-304, The SH version of the update should be wrapped in an `#if ENABLE_SH` ... `#endif`.

3. I may be missing something here, but when low_freq is updated on line 300, should it really be multiplied by `dot(bounce_direction, normal)`? For lambertian diffuse reflectance, the output should be light * cos(theta_i) / PI, but the pdf is also cos(theta_i) / PI when theta_i is generated from a cosine-weighted distribution (line 112), so shouldn't the two cancel out?

**Comment by apanteleev** [comment]
All fixed in https://github.com/NVIDIA/Q2RTX/commit/3d6dae95f674593091be67342f9bdec5f3a50d2e

Good catch, thanks!
The dot product in (3) was there because the ray distribution was uniform over the hemisphere, as you noted in (1). So these issues canceled each other out.

**Comment by DU-jdto** [comment]
Only on the first bounce (of course, the second bounce has numerous more serious issues than that), and even for that shouldn't it have been `2 * dot(bounce_direction, normal)` since the pdf for uniform sampling is `1 / (2 * PI)`? On the other hand, the sampling was only semi-uniform, so I'm not sure what the true pdf was. It's fixed now in any case.

**Comment by apanteleev** [comment]
> the second bounce has numerous more serious issues than that

Could you be more specific please?

**Comment by DU-jdto** [comment]
The main issue is that whether the second bounce contributes to the LF or specular channel should depend on whether the _first_ bounce was diffuse or specular, regardless of the type of the second bounce (which will always be diffuse at the moment). I addressed this in my local fork by storing the type of the first bounce in the unused alpha channel of the throughput texture and it produced a noticeable increase in indirect specular on more metallic surfaces (both with and without the denoiser), particularly when using higher-than-default values for pt_fake_roughness_threshold.
