### ISSUE TITLE
KHR_ray_querry + reflection visual issue on intel arc a770

### ISSUE THREAD

**Issue by quickiesdotnet** [NVIDIA/Q2RTX#253]
![khr](https://user-images.githubusercontent.com/6750289/210090970-85470e5a-14d9-4104-b3ef-738640beddd5.png)

This issue exists on 1.6 but not 1.5, in order to reproduce one must run the game on an intel gpu, select khr_ray_querry pipeline and set the reflection/refraction depth option at 1 or above. It seems like the issue started to appear with this commit:
https://github.com/NVIDIA/Q2RTX/commit/e7d671d4702fa01f8fbabaed2b4645cf78d93eb3

I tried to further look for the source of the issue but it's a slow process as I dont have full grasp on the rendering techniques used. Willing to help out if needed tho.

**Comment by res2k** [comment]
Not sure what the issue in the top circle is supposed to be, there's a
crack in the glass so nothing reflecting there...
Apart from that the other artifacts are quite obvious. Looks like some kind
of precision issue in the hardware and/or driver.
Not sure if that is something the application can work around (or should).

**Comment by quickiesdotnet** [comment]
I have recorder a video that better shows the issue on the top right:
https://streamable.com/1cjh87

My first guess was drivers as well but considering that it happens in 1.6 and not 1.5 gave me some doubts. The artifact appears or not depending on what is behind the object, the artifacts dont appear when the barrel is in front of the glass for example but they appear when the model is in front of the bsp map. And the first person gun model has the opposite issue, no issues against the bsp map but artifacts appear when a it is in front of model of the barrel.

**Comment by apanteleev** [comment]
This looks like some kind of broken interaction between threads, because the artifacts are all squares (4x4 pixels?)

Likely a driver/compiler issue, and as such, I'd recommend asking Intel about it. If you can isolate the specific git commit where the artifacts started appearing, that would help. Unfortunately I don't have access to an Intel Arc GPU and can't reproduce the issue to debug it at this time.

**Comment by quickiesdotnet** [comment]
Thanks that actually makes a lot of sense now that you mention threads, Ill dive further in the commits tomorrow and report back findings or close the issue if it is indeed an intel issue.

**Comment by quickiesdotnet** [comment]
Now fixed in Intel Arc driver 4032
