### ISSUE TITLE
need HD 'Loading' picture

### ISSUE THREAD

**Issue by djleon83** [NVIDIA/Q2RTX#265]
need HD 'Loading' picture.

**Comment by res2k** [comment]
A high-res "loading" image can be found in recent q2xp versions, so if you want to have such an image in your local copy, you could extract "gfx/loading.tga" from there: https://www.moddb.com/mods/quake-2-xp.

**Comment by RoLex** [comment]
`baseq2/q2xp0.pkx/pics/loading.tga` to be correct :-P Thanks, this was useful for me too!

**Comment by djleon83** [comment]
Thank both of you guys!
This is so helpful!
Oh and shame of my poor english, thank god you two know what i mean haha.

**Comment by RoLex** [comment]
@res2k Please close this issue :-) Btw, I see so many resolved issues, nobody closes them.

**Comment by apanteleev** [comment]
Closing.

I think it's best if the person who opened an issue closes it, but I can look at other issues and close appropriately. 
Btw, res2k is not the maintainer here, even though it might seem that way because of his activity.

**Comment by RoLex** [comment]
Oh, alright. Thank you @apanteleev :-)
