### ISSUE TITLE
Implement Crosshair Fix

### ISSUE THREAD

**Issue by gomet0** [NVIDIA/Q2RTX#274]
Great project, would be nice if there was an option to center the crosshair (as the Yamagi Quake II client)

Issue:
https://www.youtube.com/watch?v=kBty1hAEIqg

Fix:
```
* **aimfix**: Fix aiming. When set to to `0` (the default) aiming is
  slightly inaccurate, bullets and the like have a little drift. When
  set to `1` they hit exactly were the crosshair is.
```

In **\src\game\player\weapon.c** (line 72)
https://deponie.yamagi.org/quake2/quake2-8.20.tar.xz

**Comment by apanteleev** [comment]
Implemented in https://github.com/NVIDIA/Q2RTX/commit/a50fe3547c17f95537eafd42db14aa83e9efdcc1
