### ISSUE TITLE
Windows - MP2 Ground Zero crash when loading rlava1

### ISSUE THREAD

**Issue by abalfoort** [NVIDIA/Q2RTX#277]
Assertion failure in [vertex_buffer.c](https://github.com/NVIDIA/Q2RTX/blob/master/src/refresh/vkpt/vertex_buffer.c#L659):
```
src/refresh/vkpt/vertex_buffer.c:659: vkpt_light_buffer_upload_to_staging: Assertion `bsp_mesh->num_light_polys + num_model_lights < MAX_LIGHT_POLYS' failed.
```
MAX_LIGHT_POLYS is set to 4096.

Values on assertion failure:
```
		bsp_mesh->num_light_polys	5332	int
		num_model_lights	0	int
```

**Comment by abalfoort** [comment]
This only happens in Windows, not in Linux (Debian).

Originally posted here: https://github.com/abalfoort/Q2RTX/issues/7

**Comment by abalfoort** [comment]
Fixed this by increasing the MAX_LIGHT_POLYS value to 8912: commit 0eaca60

I don't know if this a preferred solution or not, but for now it seems to have solved this issue.

I'm open for better suggestions.

**Comment by apanteleev** [comment]
Thanks for reporting the issue - I just fixed it in https://github.com/NVIDIA/Q2RTX/commit/562d15118deeed3b945dbf26efd17c477378b8d2

**Comment by abalfoort** [comment]
You chose not to increase the MAX_LIGHT_POLYS value. Is there a reason to keep the value low at 4096?

**Comment by apanteleev** [comment]
The high light count was actually a bug, the map needs 764 lights with that bug fixed. And I added a warning message if the 4k limit is ever exceeded, so the game should not crash but provide actionable info.

**Comment by abalfoort** [comment]
Tested over the past two weeks and works perfectly. Thanks!
