### ISSUE TITLE
Increased noise with Spherical Triangle Sampling (commit #266)

### ISSUE THREAD

**Issue by PalmliX** [NVIDIA/Q2RTX#287]
We recently merged our fork with Q2RTX master and noticed a greatly increased amount of noise in our custom maps. I eventually managed to track down the source of the issue to this specific commit: https://github.com/NVIDIA/Q2RTX/pull/266

Doing more testing it seems that the main factor in determining the amount of noise was the number of light sources in a given scene, which is probably why it doesn't show up nearly as much in the original Q2 maps compared to our custom ones, however I was still able identify increased noise in the Q2RTX 1.7 release vs Q2RTX 1.6 in the original Q2 maps, it's very hard to see however and probably wouldn't show up in screenshots or videos due to compression.

I made a comparison video using our custom map which has many light sources in the scene. Please note that in order to see the issue better in this video I have scaled to 200% and increased the contrast in the screen recordings: https://youtu.be/aBvm6IMYFAg

I also did a comparison with the denoiser off and couldn't really notice any appreciable difference. This leads me to wonder if it's simply a matter of tuning the denoiser as opposed to this method of sampling actually producing more noise.

Another curious thing to note about this issue is that when using the "mist" flag on the emissive brushes the amount of noise seems to increase by an order of magnitude. I was originally using mist as a way to fake flame sources of light (in combination with nodraw) which are an omni source but don't present any physical barrier to the player. Since discovering this issue I have switched to using "aux" instead which accomplishes the same thing but without doubling the number of faces which "mist" does apparently (two-sided vs one-sided). When using "aux" instead of "mist" the amount of noise seems to be equal to not using mist.

**Comment by res2k** [comment]
Can you provide a standalone map that exhibits this issue?

**Comment by PalmliX** [comment]
Certainly! I made a quick test map which uses existing Q2RTX assets. I also made a version with the emissive brushes flagged as "mist" since that seems to make the issue easier to see though it's still quite obvious without. Thanks @res2k! 
[maps.zip](https://github.com/NVIDIA/Q2RTX/files/11995850/maps.zip)

**Comment by PalmliX** [comment]
One more thing to note is that this issue CAN be seen in the original maps as well, it's just harder to see, but if you go to this area which is right in the first map and switch to night mode you can see more noise in these areas when compared with 1.6. 
![image](https://github.com/NVIDIA/Q2RTX/assets/7981637/8915b91b-a25d-4d8d-bcc8-f37908b3643c)

**Comment by res2k** [comment]
> Certainly! I made a quick test map which uses existing Q2RTX assets. I also made a version with the emissive brushes flagged as "mist" since that seems to make the issue easier to see though it's still quite obvious without. Thanks @res2k! [maps.zip](https://github.com/NVIDIA/Q2RTX/files/11995850/maps.zip)

Thanks!
Could you also attach the `.map` file for the test map? Being able to make some simple adjustments may be helpful.

**Comment by PalmliX** [comment]
> Thanks! Could you also attach the `.map` file for the test map? Being able to make some simple adjustments may be helpful.

Here you go, let me know if you need anything else!
[maps.zip](https://github.com/NVIDIA/Q2RTX/files/11997070/maps.zip)

**Comment by res2k** [comment]
@PalmliX, please check PR #289 - it removed the noisiness in the test map you provided, so I think it's worthwhile to run your real maps with it.

**Comment by PalmliX** [comment]
@res2k That seems to have done the trick! I checked multiple maps and the issue appears to have been eliminated as far as I can tell. 

Thank you for your efforts on this, it's much appreciated!
