### ISSUE TITLE
Crash when starting a game or loading save save (Windows/Linux)

### ISSUE THREAD

**Issue by pppbb** [NVIDIA/Q2RTX#293]
Steps to reproduce:
Start q2rtx then go to console and start demo.
[Q2RTX_CrashReport00.txt](https://github.com/NVIDIA/Q2RTX/files/12289357/Q2RTX_CrashReport00.txt)

**Comment by pppbb** [comment]
Update: surprisingly debug build works without issues.

**Comment by res2k** [comment]
Could you either
(a) try the build here?: https://github.com/res2k/Q2RTX/actions/runs/5822525998
It does not fix the error, but should hopefully produce a more expressive crash report.
or,
(b) provide a complete callstack from your own build? (If Debug didn't crash, try RelWithDebInfo.)

Thanks!

**Comment by apanteleev** [comment]
@pppbb - can you please try the latest version in `master`? This is likely fixed with https://github.com/NVIDIA/Q2RTX/issues/296

**Comment by pppbb** [comment]
> can you please try the latest version in master? This is likely fixed with https://github.com/NVIDIA/Q2RTX/issues/296

I have built q2rtx `master` with config `Release` and it works fine now.

**Comment by apanteleev** [comment]
Thanks - closing as fixed.
