### ISSUE TITLE
wrong flashlight direction when playing demo

### ISSUE THREAD

**Issue by in-league-with-satan** [NVIDIA/Q2RTX#294]
in playdemo mode cl.predicted_angles vector remains zero, so flashlight direction calculated incorrectly

src/client/view.c
`void V_Flashlight(void)` function

if change line
`VectorCopy(cl.predicted_angles, flashlight_angles);`
to
`VectorCopy(cl.refdef.viewangles, flashlight_angles);`

it looks good

**Comment by res2k** [comment]
IIRC, `viewangles` would look somewhat odd in third person mode - it would follow the camera, not where the player is looking.

**Comment by res2k** [comment]
One (partial) solution may be to do a check `if (cls.demo.playback)` and use `cl.refdef.viewangles` in that case.
Now that would be incorrect in thirdperson in demos - if that is thing, and not completely weird in other ways (as thirdperson is also a client-side effect).

**Comment by in-league-with-satan** [comment]
tried to play with "cl_player_model 3", seemed to me both options look the same

**Comment by res2k** [comment]
You need to choose a `cl_thirdperson_angle` that differs from the default (0).
With e.g. 90 degrees it's quite obvious the flashlight points along the view direction, not the direction the player model looks.

**Comment by in-league-with-satan** [comment]
ah, yes. with `cl_thirdperson_angle` there is a difference. but why someone needs to change this angle? control becomes strange, almost unplayable

**Comment by res2k** [comment]
The angle can be used to adjust how third person mode looks.
The "why" doesn't matter - this variable is there and it should be supported.
While an angle such as 90 degrees is indeed pretty extreme and probably nobody will actually play like that for a prolonged time,
it demonstrates that using `cl.refdef.viewangles` is incorrect.
And it's incorrect independent of the actual angle.

**Comment by in-league-with-satan** [comment]
ok, i just reported the problem, but how to fix it and whether it needs to be fixed is up to you. for my purposes own fork is enough
