### ISSUE TITLE
Music files not searched in the game install directory

### ISSUE THREAD

**Issue by Lastique** [NVIDIA/Q2RTX#31]
On Linux, music only works if the ogg files are in `~/.quake2rtx/baseq2/music`, not in `<Quake II Install Directory>/baseq2/music`.

**Comment by liam-middlebrook** [comment]
Hi, as of commit https://github.com/NVIDIA/Q2RTX/commit/78e7257e1542aa8972470e046213922c728d344e `find-retail-paks.sh` file has the ability to find music files from `<Quake II Install Directory>/baseq2/music`.

You can re-run this script via Steam by selecting the `Play Find Retail Quake II Content` option when launching the game, or by right-clicking on the game in your library.

If you've installed the game through the Debian/Ubuntu package you can find this script in `/usr/share/quake2rtx/bin/find-retail-paks.sh`.

**Comment by Lastique** [comment]
This bug is not about the `find-retail-paks.sh` script but the game itself. The game does not look for music files in `<Quake II Install Directory>/baseq2/music`, where all game data is installed.

**Comment by liam-middlebrook** [comment]
Okay, that clears things up. Can you try setting the `fs_gamedir` Cvar to `<Quake II Install Directory>` at launch-time? If that doesn't work and you're comfortable building the game yourself, try to revert f05589b033f20542cebe0fbaaee2a8c7f22ae261.

**Comment by Lastique** [comment]
How can I set `fs_gamedir` on launch? None of the command line variants I tried seem to change it from `~/.quake2rtx/baseq2`.

**Comment by Lastique** [comment]
When I run the game like this:

```
./q2rtx.sh +seta fs_gamedir "$PWD"
```

I can see "fs_gamedir is read-only." in the console output, and `fs_gamedir` in the in-game console is still `~/.quake2rtx/baseq2`.

**Comment by CKWarner** [comment]
As far as I can tell, it's because the ogg.c is using fs_gamedir directly (which is necessarily the home directory), rather than the internal Quake filesystem.

**Comment by TobiasKarnat** [comment]
This is fixed in my patch here: https://github.com/NVIDIA/Q2RTX/issues/87#issuecomment-931558084
