### ISSUE TITLE
[regresssion] Graphic does not render correctly

### ISSUE THREAD

**Issue by runlevel5** [NVIDIA/Q2RTX#312]
I can confirm https://github.com/NVIDIA/Q2RTX/pull/308 has caused regression to the game renderer

Before

![Screenshot from 2023-08-26 01-20-31](https://github.com/NVIDIA/Q2RTX/assets/135605/75f86b94-3a96-4086-b324-bedb4ed5746d)

After

![Screenshot from 2023-08-26 01-39-08](https://github.com/NVIDIA/Q2RTX/assets/135605/274c9d44-baf0-49dc-9aee-7381fd592697)

### Hardware Information:
- **Hardware Model:**                              (null)
- **Memory:**                                      61.4 GiB
- **Processor:**                                   POWER9, altivec supported × 32
- **Graphics:**                                    AMD Radeon™ RX 6600 XT
- **Disk Capacity:**                               1.0 TB

### Software Information:
- **Firmware Version:**                            (null)
- **OS Name:**                                     Fedora Linux 40 (Workstation Edition Prerelease)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.beta.1
- **Windowing System:**                            X11
- **Kernel Version:**                              Linux 6.5.0-0.rc6.20230818git0e8860d2125f.47.fc40.ppc64le

cc @res2k wondering if you get the same issue on your Linux box

**Comment by res2k** [comment]
Can't reproduce.
On Windows right now, but can try Linux later.
However, as the shaders have changed, please confirm you're using up-to-date compiled shaders (`.spv` files), and not, say, those from the last release.

**Comment by res2k** [comment]
Can't reproduce on Linux either.
Not that that's saying much, considering pretty much everything else is different.

**Comment by apanteleev** [comment]
Latest `master` works fine for me also. Make sure that your shaders are rebuilt.

**Comment by runlevel5** [comment]
Please excuse my ignorance, how could I package the shaders?

AFAIK there is https://github.com/NVIDIA/Q2RTX/blob/b3cd8597aabd94cb95ddac5a9b70c4e658aaa306/setup/package_shaders.bat#L5

which basically compress the `baseq2/shader_vkpt` to produce `shaders.pkz`.

**Comment by res2k** [comment]
Well, as that script suggests, you could use any tool that can generate ZIP archives to do the packaging (`.pkz` files are just zip archives with a different extension.)
However, that may not actually be necessary: you just need to make sure the "shader_vkpt" directory generated by the Q2RTX build is in the right place - which would be the game data directory, `baseq2` (there e.g. `blue_noise.pkz` should be located as well).

**Comment by runlevel5** [comment]
Great thanks for helping me. I am closing this issue now.
