### ISSUE TITLE
 (Linux) Failed request: bad value

### ISSUE THREAD

**Issue by 10010101001** [NVIDIA/Q2RTX#34]
When I launch q2rtx, I get an error message:

> ]X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  83
  Current serial number in output stream:  84
AL lib: (EE) alc_cleanup: 1 device not closed

Specs:
Core i7 
GTX 1050 (with nvidia-418)
Ubuntu 1804

**Comment by CKWarner** [comment]
The 1050 doesn't have vk_nv_raytracing implemented, only the 6 GB 1060 and above.

**Comment by 10010101001** [comment]
Thanks!
