### ISSUE TITLE
Announcement: SIGGRAPH presentation on lighting in Q2RTX

### ISSUE THREAD

**Issue by apanteleev** [NVIDIA/Q2RTX#38]
Hi everyone,

This year at SIGGRAPH, I will be giving a talk about lighting in Quake II RTX. The talk will include details about importance sampling of polygonal lights, geometry processing, and sky lighting.

Wednesday, July 31st, 2019, 9:00 AM:
https://www.nvidia.com/en-us/events/siggraph/schedule/?talkid=sig201973101

Slides and session recording should be available later.

Also, if you'll be at SIGGRAPH on Tuesday evening or on Wednesday and want to talk about something Q2 related, you can send me an email: alpanteleev @ nvidia . com

-- Alexey Panteleev
Lead engineer of Q2RTX

**Comment by Beilerbey** [comment]
Could you post a link to the recording? I'd be very interested, thanks!

**Comment by apanteleev** [comment]
Sure, I'll post the links once Nvidia publishes the recording and the slides.

**Comment by apanteleev** [comment]
The video recording is now available here: 
https://developer.nvidia.com/siggraph/2019/video/sig925 

Other recordings of SIGGRAPH 2019 presentations are also available:
https://www.nvidia.com/en-us/events/siggraph/schedule/

(Developer account required)

**Comment by Beilerbey** [comment]
Thanks a lot for the heads up, I don't have a developer account but I was able to watch your presentation, along with other two, a couple of weeks ago by following the first link. I guess they got locked down now, maybe to preserve bandwidth, but they were very interesting even for a pleb like me.
