### ISSUE TITLE
Quake 2 RTX Demo Crashing on Start

### ISSUE THREAD

**Issue by deltamish** [NVIDIA/Q2RTX#39]
Says's Couldn't initialize Vulkan.

Running on RTX 2060, Ryzen 5 2600 and 16 gig RAM

**Comment by SkacikPL** [comment]
Try doing a clean install on newest NVIDIA drivers and install vulkan runtime separately.
https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/latest/windows/vulkan-runtime.exe

**Comment by Squall-Leonhart** [comment]
if  you swapped from a Radeon the system has still got a radeon vulkan json registered in the system, so DDU the radeon driver and test first before doing it with the nvidia driver.

Radeon drivers are really the only time you need to run ddu, nvidia's own uninstaller handles most of it just fine.

**Comment by gitowiec** [comment]
I have the same issue. I am trying to run Quake 2 RTX Demo on newly bought Asus TUF FX505 with Ryzen 3750H and Geforce RTX2060. I just installed Steam, all Windows 10 updates and Quake RTX. All I get is
![obraz](https://user-images.githubusercontent.com/1553195/70362993-129aae00-1887-11ea-8412-546cedcc9df8.png)

**Comment by Squall-Leonhart** [comment]
Ryzen notebooks ship with a faulty APU driver install, update it with the package from the AMD site.

**Comment by jimiontu** [comment]
hi, i had the same problem, same driver, same laptop:)), all you have to do is to uninstall the driver and restart the laptop:))
