### ISSUE TITLE
Support for OGG OST

### ISSUE THREAD

**Issue by Siphonay** [NVIDIA/Q2RTX#4]
(this thread originally concerned both the OST and cutscenes, but has been renamed so they can be split in two separate issues)

Hello! I'd love to experience a casual playthrough of Quake II with RTX enabled. However, Q2RTX does not feature cutscenes (despite them showing in the trailer) or any kind of music.

Would it be possible to implement the playback for those two things in Q2RTX?

**Comment by Vash63** [comment]
I was just about to open an issue request for music. It would be _really_ nice from a usability / experience standpoint to have the full game without missing out on music. Cutscenes would be nice too.

**Comment by marty28** [comment]
It has ogg music playback support but they built the binary with it disabled by the looks of it. Nvidia can you please release a new Steam build with #define OGG

https://github.com/NVIDIA/Q2RTX/blob/master/src/client/sound/ogg.c

**Comment by Siphonay** [comment]
I don't know if they accept it but if it's as simple as that, I'll make a pull request later today

**Comment by Vash63** [comment]
Oh cool, have you tested that it works? I submitted a tiny 1 line PR to fix the installer breaking on white space ("Quake 2") and they accepted it very quickly so if it works I'd hope the same for your fix.

**Comment by Siphonay** [comment]
Just adding #define OGG doesn't work, I need to also define all the functions in ogg.c as well as the struct type ogg_seek_t, for which I have no clue yet as to what it contains. I'll take a closer look at it later today.

**Comment by apanteleev** [comment]
Even if you do enable OGG support in the game and we merge it, where do you suggest the users will obtain the music in OGG? NVIDIA doesn't own the copyright for the music and therefore cannot distribute it. Sure, one can rip the game CD or find it online or something, but that's not very user friendly.

**Comment by DaveVoyles** [comment]
@apanteleev The best bet may be to add a small note in the README.md to illustrate that the music is not included because the disc is required. I'd imagine that many (most?) people playing do not realize that it is not included, and particularly on the Steam version.

We could follow that note up with a suggestion to Google 'Quake II ost download', without pointing to the actual site/location of the host, that it could work around the legal issue.

**Comment by Siphonay** [comment]
I did not realize the music wasn't included in the Steam version...

However, what it has that Quake II RTX hasn't are video cutscenes. It could be nice to have them in Quake II RTX.

**Comment by jonnypanic** [comment]
I guess many people, like me, already have the .ogg files, cd, or GOG version with music, unless they just bought the game to try out rtx. If not there are guides explaining how to convert etc, on the quake 2 steam forums. As suggested above, a note in the readme saying where to put the files you legally own would suffice.

**Comment by slavap** [comment]
@apanteleev GOG version has all music as ogg files, just implement support please and add link to GOG to allow people to purchase the proper version :-) https://www.gog.com/game/quake_ii_quad_damage

**Comment by Chaython** [comment]
> Even if you do enable OGG support in the game and we merge it, where do you suggest the users will obtain the music in OGG? NVIDIA doesn't own the copyright for the music and therefore cannot distribute it. Sure, one can rip the game CD or find it online or something, but that's not very user friendly.

During setup you can tell it to install the full game, via an existing install. IDK why they didn't merge the music during installation.

**Comment by apanteleev** [comment]
I have an experimental local branch that enables OGG support, but only in software audio mode (not OpenAL). Need to clear up a few things before releasing it though.
Asking the user to copy the music manually seems reasonable.

**Comment by apanteleev** [comment]
Music support has been added in this and some subsequent commits: https://github.com/NVIDIA/Q2RTX/commit/b6f603109078d9adcc37fdb1c2d068a7204e5552
Should be available in the next published binary build.

**Comment by Vash63** [comment]
Great, glad to see it. I think for documentation the same thing that Yamagi's github uses would suffice for me (just to make clear the location and filenames necessary):

https://github.com/yquake2/yquake2/blob/master/doc/02_installation.md#music-extraction

#### Using a Generic CD Extractor
1.  Install a CD extractor (for example CDex) and set it to OGG/Vorbis files. Quality factor 6 (192 kbit/s) is usually more than enough.
2. Put the Quake II CD into the CD drive and extract the files.
3. The files must be named after the corresponding CD track: CD track 02 becomes the file 02.ogg, CD track 03 becomes the file 03.ogg and so on. On both the Quake II and the Addon CDs track 01 is the data track and thus can't be ripped.
4. Put these files into the corresponding subdirectory:

    - baseq2/music for Quake II.
    - xatrix/music for The Reckoning.
    - rogue/music for Ground Zero.

**Comment by josestefan** [comment]
Video cutscenes and soundtrack should be two separate issues.

**Comment by Siphonay** [comment]
@josestefan fair point, I've renamed this issue and created a second one

**Comment by warrengc3** [comment]
Any eta on a new build and release?

**Comment by picaron** [comment]
please add this! its unplayable without the music!

**Comment by apanteleev** [comment]
@picaron OGG support has been added, see above.

The new build should be published sometime next week.

**Comment by apanteleev** [comment]
In the meantime, you can play the OST in any music player app running in background.

**Comment by picaron** [comment]
thanks for the update @apanteleev I'll wait for the new build

**Comment by warrengc3** [comment]
Looking forward to the update!  Thanks for the quick response.

**Comment by SkacikPL** [comment]
I built the new version with OGG support, i _strongly_ recommend adding separate volume control for musing as on default volume it's way too loud.

**Comment by apanteleev** [comment]
There is a separate control: `ogg_volume` cvar. And there will be a menu item for that control; the menu definition `q2rtx.menu` file is just not part of the github repository because it lives in baseq2.

**Comment by jdPhobos** [comment]
Strange but not working. I take pak* and music from GOG, I type commands to the console (they are in the configuration file). No effect. Renamed music to 02, 03 and place near exe. No effect. Switched the sound engine too.

Somewhere I screwed up or a problem in my sound card (Asus Xonar DG), or maybe something in the code. Help.

**Comment by picaron** [comment]
downloaded the update via Steam, OGG music working like a charm now

I believe this issue can be closed now

**Comment by warrengc3** [comment]
I can validate received the update from steam and worked perfectly for me as well!

Great work!  Thanks so much!

**Comment by Lastique** [comment]
On Linux, music only works if the ogg files are in `~/.quake2rtx/baseq2/music`, not in `<Quake II Install Directory>/baseq2/music`.

**Comment by josestefan** [comment]
> 
> 
> On Linux, music only works if the ogg files are in `~/.quake2rtx/baseq2/music`, not in `<Quake II Install Directory>/baseq2/music`.

This should probably be a new issue, as the original issue should be closed.

**Comment by Lastique** [comment]
No problem, created https://github.com/NVIDIA/Q2RTX/issues/31.

**Comment by apanteleev** [comment]
Closing.

**Comment by Marat-Tanalin** [comment]
#24 is a related feature request regarding support for _lossless_ CD-quality music (FLAC or Wave).
