### ISSUE TITLE
CONFIG_GL_RENDERER Off

### ISSUE THREAD

**Issue by FrankTyph** [NVIDIA/Q2RTX#412]
I tried to build with:
OPTION(CONFIG_GL_RENDERER "Enable GL renderer" OFF)
but in compilation VS2022 does not find the definition of MIPLEVELS.

Sorry for my google translation (I'm italian) :)

**Comment by apanteleev** [comment]
Fixed in 642644cd875b0ba5a2c4ea57281c8aa99d2764f3
