### ISSUE TITLE
Unable to compile q2rtx.exe on Windows 11

### ISSUE THREAD

**Issue by abalfoort** [NVIDIA/Q2RTX#415]
Windows is updated.

Installed:
VulkanSDK-1.3.296.0
Git-2.47.0.2-64-bit
cmake-3.31.0

Commands used:
```
git clone --recursive https://github.com/NVIDIA/Q2RTX.git
cd Q2RTX
mkdir build
cd build
cmake -S .. -B .
cmake --build .
```

See log for details:
[build.log](https://github.com/user-attachments/files/17688530/build.log)

baseq2/gamex86_64.dll and q2rtxded.exe are built, but not q2rtx.exe

**Comment by res2k** [comment]
Please try with #416

**Comment by abalfoort** [comment]
That fixed it.
Thanks!
