### ISSUE TITLE
Laser beams don't emit lights?

### ISSUE THREAD

**Issue by SkacikPL** [NVIDIA/Q2RTX#43]
By default it seems that laser beams don't behave like light sources at all, only exception is the player railgun beam.

As a test i tried porting over this behavior to all laser beams and got something like this:
https://streamable.com/87v3g

It works and in general is better than not having them at all (at least IMO) though it obviously means running into 32 dynamic lights limit in nearly every instance.
To work around that i made the lights spawn only if they're within 300 units of the camera.

There may be a better way of achieving this or at least i would hope so as having them emit lights makes them less shallow looking.

**Comment by apanteleev** [comment]
Implemented in https://github.com/NVIDIA/Q2RTX/commit/d8bfacb64a57a3917357fb72ac99435cdca74548

Each laser beam is now converted to 6 triangular lights.
The effect and its brightness are controlled by the `pt_beam_lights` cvar.

Thanks for pointing this out!

**Comment by apanteleev** [comment]
Before: 
![image](https://user-images.githubusercontent.com/11079788/62810221-24736c80-bab2-11e9-8ed7-79e544e43bea.png)

After:
![image](https://user-images.githubusercontent.com/11079788/62810257-2806f380-bab2-11e9-92ee-e55057241860.png)
