### ISSUE TITLE
More artwork needed

### ISSUE THREAD

**Issue by CKWarner** [NVIDIA/Q2RTX#46]
The new Steam Library interface is rolling out now, with different-sized images to before. Q2RTX doesn't yet have images of the appropriate size for the new interface.

Details of the requirements are [here](https://steamcommunity.com/groups/steamworks/announcements/detail/1597002662762032240).

**Comment by apanteleev** [comment]
Thank you, we are aware of this. An update for Q2RTX is coming soon, and the Steam library images should be updated with that.

**Comment by CKWarner** [comment]
Steam update landed today. Updated artwork included.
