### ISSUE TITLE
compiling issue

### ISSUE THREAD

**Issue by BielBdeLuna** [NVIDIA/Q2RTX#49]
in Ubuntu 19.10 with cmake I got the following compiling error:

`[ 84%] Building C object src/CMakeFiles/client.dir/refresh/vkpt/bsp_mesh.c.o
/home/biel/games/src/Q2RTX/src/refresh/vkpt/bsp_mesh.c:28:10: fatal error: tinyobj_loader_c.h: El fitxer o directori no existeix
   28 | #include <tinyobj_loader_c.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/client.dir/build.make:2209: src/CMakeFiles/client.dir/refresh/vkpt/bsp_mesh.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:643: src/CMakeFiles/client.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`

**Comment by apanteleev** [comment]
Looks like you haven't updated the submodules when you pulled the update over your previous working copy. Please run `git submodule update --init`.

**Comment by BielBdeLuna** [comment]
ok thanks

**Comment by apanteleev** [comment]
@BielBdeLuna - please close the issue if it has been resolved for you.

**Comment by BielBdeLuna** [comment]
indeed, solved! :+1:
