### ISSUE TITLE
Support for additions

### ISSUE THREAD

**Issue by maximus105** [NVIDIA/Q2RTX#50]
Will the following patches support the additions of Ground Zero and The Reckoning? And how to restore the video cut scenes that were in the original Quake 2? Weapon models were made poorly, especially blaster, super shotgun, chaingun, hyperblaster, railgun, bfg9000. They shine too much, as if oiled. And new weapon models are poorly made. Original weapon models were better. And what other corrections and additions are planned to be done in the near future for Quake 2 RTX?

**Comment by apanteleev** [comment]
Expansion pack support is unlikely to be added, see the discussion here: https://github.com/NVIDIA/Q2RTX/pull/28

Cut scenes are not supported by Q2PRO, and we didn't add support for them either. No current plans to add that, but a pull request with such support would be welcome.

Most weapon models were taken from the Q2XP mod, and their textures somewhat modified to add the chrome effects. Our custom models are: super shotgun, railgun, BFG, and flare gun. You are welcome to make an alternative weapon model or texture pack, though.

**Comment by apanteleev** [comment]
Also, see issue https://github.com/NVIDIA/Q2RTX/issues/11 for the cut scenes discussion.
