### ISSUE TITLE
Incorrect handling of multiple monitors

### ISSUE THREAD

**Issue by Raptor85** [NVIDIA/Q2RTX#54]
In multiple monitor setups geometry is hardcoded to only query monitor number 0, and hardcoded to reset window location to x:0 y:0, ignoring system primary monitor settings, this causes q2rtx to open fullscreen on the incorrect monitor on many layouts with no way to change which monitor it opens on.  Bug is centered in VID_GetFullscreen in refresh.c  and the SetMode functions in SDL2's video.c 

Steam thread of issue here with temporary workaround [https://steamcommunity.com/app/1089130/discussions/0/1754646083691358061/?tscn=1575797213](https://steamcommunity.com/app/1089130/discussions/0/1754646083691358061/?tscn=1575797213)

**Comment by apanteleev** [comment]
Commit https://github.com/NVIDIA/Q2RTX/commit/acaf72f226e169775c7bf66fccda6cfedbcb3efd adds cvar `vid_display` that allows you to select the full screen monitor. Is that good enough?
