### ISSUE TITLE
Missing material in 1.2.1

### ISSUE THREAD

**Issue by Beilerbey** [NVIDIA/Q2RTX#55]
In the Outer Courts, after using the pipe that sucks you up to the flooded room where you can find the hidden data spinner, after jumping over the retractable brigde and following the corridor, there is a piece on the ground that appears matte black.

![20191220203635_1](https://user-images.githubusercontent.com/53339496/71312827-2a9a3200-2430-11ea-836c-96fefbb487f9.jpg)

**Comment by apanteleev** [comment]
Fixed in https://github.com/NVIDIA/Q2RTX/commit/cd19b22b7c7fbfbfc606e8dcee5d90042ad050f2

The material was not missing, but that step is modeled with triangles facing both inwards and outwards, so it was self-shadowing under the old ray offset logic.

Thanks for reporting this!

**Comment by Beilerbey** [comment]
Awesome, thanks!
