### ISSUE TITLE
Graphics issue

### ISSUE THREAD

**Issue by maximus105** [NVIDIA/Q2RTX#59]
During the game, at random, the picture becomes as if in gray. Most often this happens after a quick save when you press the F6 key, closer to the middle of the game or to the end of the game, for example, on the Cooling Facility map.
![q2rtx_2019_12_31_11_52_44_596](https://user-images.githubusercontent.com/58270614/71617622-93b63e00-2bc4-11ea-903b-683d50e6ef1c.png)
![q2rtx_2020_01_01_17_31_12_498](https://user-images.githubusercontent.com/58270614/71643088-6c8f6780-2cbd-11ea-9d12-79331b0d398d.png)
After leaving Quake 2 RTX and restarting, the gray picture also remained. The problem disappeared only after I took the q2config.cfg file from version 1.1.0 and replaced the current q2config.cfg file with it. Sometimes the problem is solved if you go to the desktop and start the game again.

**Comment by enigma7483** [comment]
This is not an issue with the game... try pressing the F7 key it will toggle the textures on and off in the manner that you have described... The F7 key was probably wrongfully pressed when pressing the F6 key.
