### ISSUE TITLE
Why region locked?

### ISSUE THREAD

**Issue by TheAifam5** [NVIDIA/Q2RTX#6]
Hey,

Just why?!

Steam: This item is currently unavailable in your region
Official NVIDIA Page: "Game Over   DIE MISSION, DIESE SEITE AUFZURUFEN, IST GESCHEITERT."

So then why this GitHub repo is not region locked like other sites?

Regards,
TheAifam5

**Comment by Chaython** [comment]
Perhaps quake 2 was banned in your region, all other releases include quake 2's shareware demo, this git includes no media

**Comment by TheAifam5** [comment]
I love Germany -.-

**Comment by apanteleev** [comment]
Region locked because the game is still banned in Germany. Sorry.
Closing the issue.
