### ISSUE TITLE
Game stutters every 3 seconds on Linux

### ISSUE THREAD

**Issue by gyroninja** [NVIDIA/Q2RTX#62]
Every 3 seconds my game stutters. This freeze can last a little over a quarter of a second. While tracking down the issue I found out that it was a problem with SDL2 and has already been resolved 2 months ago upstream. https://github.com/spurious/SDL-mirror/commit/59728f9802c7869a9b47d6176296086dc0d00d45

I have validated that this fix does indeed stop the stuttering I am getting. Could you please bump the version of SDL2 that is being used to at least a version including that commit? The constant stuttering makes the game almost unplayable.

**Comment by apanteleev** [comment]
SDL2 has been updated in https://github.com/NVIDIA/Q2RTX/commit/3673c34b58ee8a2ed21ebd2e9ddcb70845f14599

Thank you for tracking it down!

**Comment by philipl** [comment]
Thanks for tracking this down! I had got to the stage of verifying my local build was stutter free (because it uses the system SDL) but not past that.
