### ISSUE TITLE
Feature Request: Please build one of the existing MP bots to support Quake 2 RTX

### ISSUE THREAD

**Issue by Axonimpulse** [NVIDIA/Q2RTX#64]
Hello, 

 Quake 2 RTX weighed heavily in my decision to purchase a RTX 2080 Ti card. Kind of ironic since 20 years ago I got my Riva TNT 2 card also because of Quake 3 and Quake 2. 

 Anyway, I used to love chilling and playing Quake 2 versus bots many years ago and would also love to do the same in Quake 2 RTX.

 I've tried building from source (Visual Studio 2015) the x64 DLL for one of the mods that include bots.  I had trouble building the Gladiator bot. Acebot and 3ZB2 bot were built successfully but when I load the DLL they give the same error regarding 'max_edicts': "game DLL returned bad number of max_edicts". 

  I have almost zero real world programming experience and I don't know how to fix this. I've spent more than 10 hours poking through the source code of the bots trying to figure it out but I had little success.  

  The source for these bots was written for the original Quake 2 (v 3.20 I presume), not for the Q2PRO client. 

  Could someone more knowledgeable please build a gamex86_64.dll that has bot support ?  

  Thank you very much !

 I got the gladiator bot source code from here: 

 https://mrelusive.com/oldprojects/gladiator/download.shtml.htm 

 The 3ZB2 and acebot source code from here: 

 http://www.angelfire.com/mt2/quakebots/downloads.html 

Gladiator bot or 3ZB2 bot would be preferred because they also have higher difficulty levels.

**Comment by Axonimpulse** [comment]
Finally managed to make the 3ZB2 bot work with Q2RTX v1.3. Will post link to the bot mod gamex86_64.dll that I managed to build. Played for a few hours, everything seems ok.  
Thank you for Q2RTX, love it !

**Comment by gribbs88** [comment]
Nice job!

**Comment by Axonimpulse** [comment]
Link to the compiled binary : 

https://www.moddb.com/mods/3zb2-bots-for-q2rtx/downloads

All credit goes to the original 3ZB2 bot creators. With my limited experience, I just compiled their code and built the DLL.

Link to some gameplay action vs the bots : 

https://www.youtube.com/watch?v=2v1bqn3_T_8

Big thanks to the nVidia Q2RTX team for this awesome remaster, fingers crossed that you will continue to add features. 
I'd really, really want to see the flow effects integrated back in.

**Comment by RoLex** [comment]
@Axonimpulse

There is an issue with your game, mentioned here: https://github.com/NVIDIA/Q2RTX/issues/192

Could you please share the source, or atleast tell whan needs to be changed in the 3ZB2 game source for ability to play it with Q2RTX/Q2Pro?

Maybe I could solve this myself, but I'm not there yet. So any hints would be nice.

Regards.
