### ISSUE TITLE
Make it run on all config ?

### ISSUE THREAD

**Issue by PowaBanga** [NVIDIA/Q2RTX#67]
It should be good that we can make it work on all others computers configuration, who do not have rtx graphics card, simply by unactive rtx effect in config.

If the minimum requierment was like in q2pro, we can easily create a new realase of standalone mods for that everybody can play with.

Or maybe should you offer an RTX graphic card to me for that i can create one for the dday mod :D

**Comment by Squall-Leonhart** [comment]
it runs on pascal, volta and turing graphics cards.

**Comment by PowaBanga** [comment]
not working on mx150, or without avanced graphic card...

**Comment by Squall-Leonhart** [comment]
4GB ram required.

**Comment by PowaBanga** [comment]
I have 8 Gb...

**Comment by Squall-Leonhart** [comment]
the mx150 is 1 or 2GB vram.

**Comment by PowaBanga** [comment]
ha yeah vram yes. This change absolutly nothing at that is said previously.

**Comment by Squall-Leonhart** [comment]
um, yeah it does.

RT requires 4GB's minimum, even the 1060 3GB can't do it.

**Comment by PowaBanga** [comment]
no it doesn't. I understand what you said, I am not stupid. And i think that you did undersdant what I suggest in my first message.

But thank you very much for this technical informations.

**Comment by apanteleev** [comment]
The game runs on the same configs that Q2PRO does when the OpenGL renderer is used. It can be forced by adding `+vid_rtx 0` to the command line on the first run.

Closing.
