### ISSUE TITLE
Dynamic lighting issue in photo mode

### ISSUE THREAD

**Issue by Beilerbey** [NVIDIA/Q2RTX#75]
I was playing around with photo mode yesterday and I noticed an issue with dynamic lighting coming from guns: once photo mode is enabled the light coming from "muzzle flash" fades away as the samples accumulate, if the camera is moved it gets scrapped entirely. I'm including screenshots, these are taken using cylindrical projection but the same happens with normal perspective.

![20200419031804_1](https://user-images.githubusercontent.com/53339496/79686257-5fcc5a80-823f-11ea-8916-a9e1b4ca4566.jpg)
![20200419031822_1](https://user-images.githubusercontent.com/53339496/79686277-7d012900-823f-11ea-8a61-58768e68b5db.jpg)
![20200419031855_1](https://user-images.githubusercontent.com/53339496/79686282-88545480-823f-11ea-9777-1aaa80e86f61.jpg)
![20200419031910_1](https://user-images.githubusercontent.com/53339496/79686286-90ac8f80-823f-11ea-8e14-ae6b8d365ae2.jpg)

**Comment by apanteleev** [comment]
Fixed in https://github.com/NVIDIA/Q2RTX/commit/4964247ffe185ca2cefe53adde0b444194f004f8 
Thank you for reporting this issue!

![image](https://user-images.githubusercontent.com/11079788/80136781-0d4cb000-8557-11ea-8bb3-13fb18d2e6b2.png)

**Comment by Beilerbey** [comment]
Awesome, thanks!
