### ISSUE TITLE
No game data files detected

### ISSUE THREAD

**Issue by Superlee506** [NVIDIA/Q2RTX#76]
I build successfully this project on ubuntu16.04, when I run "./q2rtx":

"FATAL: No game data files detected. Please make sure that there are .pak files in the game directory: /home/lichao/.quake2rtx/baseq2."

Do I need to install the game seperately?

**Comment by apanteleev** [comment]
Yes, you need to install the game data files from either the shareware demo, or the full quake 2 game. The pak files should be in baseq2/ along with the q2rtx-specific media files. See (3) in the build instructions: https://github.com/NVIDIA/Q2RTX#build-instructions
