### ISSUE TITLE
FUNC_BMODEL Animated texture playback

### ISSUE THREAD

**Issue by PalmliX** [NVIDIA/Q2RTX#79]
Animated textures don't play back correctly on func_bmodel. Neither the "ANIMATED" or "ANIMATED FAST" spawnflags work. To be clear, the animated texture does animate, but seems to be stuck cycling between a few frames. Not sure if this was ever used in the Quake 2 SP campaign, this is for a custom map.

**Comment by OmegaMinus1** [comment]
Skipping frame zero in the frame walk down, makes the last frame play twice is my best conclusion. Changing this file will give you opengl matched playback frames. ** denotes ** the single change

q2rtx\src\refresh\vkpt\shader\instance_geometry.comp

```
			int frame = instance_buffer.bsp_mesh_instances[id].frame.x;
			if(frame > 0)
			{
				uint material = t.material_id;
				MaterialInfo minfo = get_material_info(material);
				frame = frame % int(minfo.num_frames);

				while(true) {
					material = minfo.next_frame;
					frame -= 1;
					**if(frame > 0)**
						minfo = get_material_info(material);
					else
						break;
				}
				
				t_i.material_id = material | (t.material_id & ~MATERIAL_INDEX_MASK); // preserve flags
			}
			else
			{
				t_i.material_id    = t.material_id;
			}
```
Change to this:

			int frame = instance_buffer.bsp_mesh_instances[id].frame.x;
			if(frame > 0)
			{
				uint material = t.material_id;
				MaterialInfo minfo = get_material_info(material);
				frame = frame % int(minfo.num_frames);

				while(true) {
					material = minfo.next_frame;
					frame -= 1;
					**if(frame >= 0)**
						minfo = get_material_info(material);
					else
						break;
				}
				
				t_i.material_id = material | (t.material_id & ~MATERIAL_INDEX_MASK); // preserve flags
			}
			else
			{
				t_i.material_id    = t.material_id;
			}

**Comment by PalmliX** [comment]
I can confirm this works! The bmodel (func_wall) seems to be playing animated textures at the correct frame rates for both animation modes (5hz and 10hz) though it's not synced with playback on world brush models, which isn't an issue for my use case.

**Comment by apanteleev** [comment]
The long animated sequences have been fixed yesterday in https://github.com/NVIDIA/Q2RTX/commit/71dcb8ad06db3409f98c10f873619707a54d270a 
Can this be closed?
