### ISSUE TITLE
Building with gcc 10+

### ISSUE THREAD

**Issue by byte1024** [NVIDIA/Q2RTX#80]
Currently building fails when using gcc 10. Fedora 32 uses this version and eventually others should.

Seems to be a common issue and using -fcommon with C_FLAGS works around the problem.

Example:
`/usr/bin/ld: ../extern/SDL2/libSDL2.a(SDL_windowevents.c.o):(.bss+0x8): multiple definition of 'WAYLAND_wl_proxy_get_user_data'; ../extern/SDL2/libSDL2.a(SDL_events.c.o):(.bss+0x8): first defined here
`

**Comment by apanteleev** [comment]
GCC 10 build is fixed in release 1.4.0. Closing.
