### ISSUE TITLE
Direct sunlight not bouncing off enemies

### ISSUE THREAD

**Issue by randomoneh** [NVIDIA/Q2RTX#82]
Why is this so? I thought at least one bounce was used?
I tested this by pausing when enemy was standing bathed in light and shadow of the wall was right in front of him. That shadow was supposed to be illuminated. Yet... nothing.

Sorry for shitty drawing, I'm on my phone without access to my PC currently.

![Project Capture-01](https://user-images.githubusercontent.com/70566113/91831285-2c192c80-ec44-11ea-83bb-eec58092b34d.jpeg)

**Comment by apanteleev** [comment]
It is bouncing off of enemies, but the bounce intensity is just dimmer than one might expect. Often it's overwhelmed by the diffuse illumination from the sky visible through the same window. Maybe the sky is too bright relative to the sun though.

Here's a comparison, left to right: 

a) normal rendering mode; 
b) no illumination from the sky - you can see the light bouncing from the enemy; 
c) no illumination from the sky plus all surfaces are assumed to be white for secondary rays, which makes indirect lighting brighter but incorrect.
![image](https://user-images.githubusercontent.com/11079788/95664504-5096dd00-0afd-11eb-9d5f-0fa03dc5f4bb.png)

**Comment by apanteleev** [comment]
Better example - all the default rendering settings, real-time mode, with the enemy and without. This is from the `command` map.

![image](https://user-images.githubusercontent.com/11079788/95664614-6eb10d00-0afe-11eb-9696-54259d30d167.png)

**Comment by Calinou** [comment]
This issue can probably closed now, seeing it's not a bug and works as intended.
