### ISSUE TITLE
HDR output

### ISSUE THREAD

**Issue by simonbuchan** [NVIDIA/Q2RTX#83]
Having just got an HDR-capable monitor, I of course went down the list of games to see what supported it - to my mild surprise, Q2RTX wasn't one of them!

After figuring out the very basics of doing HDR in Vulkan on my own toy project, I took a swing at the source to see how plausible it would be to add it to this: to my surprise, simply adding `VK_FORMAT_R16G16B16A16_SFLOAT` to `acceptable_formats` in `create_swapchain()` and setting `\tm_enable 0` to get the raw HDR data on screen was enough to get some pretty damn good results! Apparently the physically accurate lighting work already done mean that without the tonemapping crushing the range you get pretty good results when in the right environments.

Strictly though, `VK_EXT_SWAPCHAIN_COLOR_SPACE_EXTENSION_NAME` should also be added to `vk_requested_instance_extensions`, which for my screen means it uses the declared surface format color space of `VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT`. Not exactly sure what the interpretation is without it, certainly with the extension enabled it is darker, implying that it is no longer applying sRGB gamma correction, as implied by the color space name (presuably the SRGB is the value of the primaries). I'll need to look into what the right thing here is, since `IMG_TAA_OUTPUT` should be linear already... I might just be confused.

So far the main issues I have hit are:
* Obviously, without *any* tonemapping the results are not optimal, morning and day times the sky is blown completely to white on my fairly typical HDR monitor, which is probably accurate, but not ideal. Some readable areas with `\tm_enable 1` become uncomfortably dark, though still visible. I'm not sure where the state of the art is here, but from what I've seen one approach is roughly the same as the existing logic, but with a configurable output range, rather than 0-1 to avoid monitor clipping, and a configurable paper white brightness to scale the exposure to match (Though everyone seems to be doing it differently right now). Maybe I'll take a stab at this, the tonemapping shader doesn't seem too confusing, but my early blind stabs were pretty unsuccessful at getting anything good out (I can get HDR values just by disabling the clamp at the end of the apply and using "out of range" values for `tm_*` cvars, but they all looked terrible - I probably just need to sit down and re-figure out the maths)
* With resolution scaling, there's a solid black line (one input pixel thick) around the blown-to-white sky and other lights, due to the lanczos filtering overshooting with the huge value step. Not sure how much of an issue this will be with "proper" tone mapping to avoid monitor clipping.
* No screenshots - proximate issue is `IMG_ReadPixels: unsupported swap chain format` but there's a whole chain of issues to figure out, eg. color space metadata and HDR image formats or tonemapping configuration on output. To be fair, Windows doesn't support HDR screenshots either, AFAICT.
* UI elements are overly dark, though not uncomfortably so, when the swapchain color space extension is enabled. Seems like an easy fix, if not corrected elsewhere.

**Comment by Rroff2** [comment]
It looks ridiculously good - I had to make some modifications (sadly don't really know what I'm doing as it isn't an area of programming I'm familiar with so I just played around by trial and error until it did something useful) to avoid it just saturating the scene with white from the sunlight and taking a photo of my display doesn't really cut it in portraying what path tracing + HDR in this game can do.

![20201209_033124](https://user-images.githubusercontent.com/75708770/101573049-231cc180-39d0-11eb-935a-89fb78326d56.jpg)

**Comment by res2k** [comment]
Hey @simonbuchan, @Rroff2, I did some more HDR-related work here: #159 
Could you check it out and provide some feedback?

**Comment by Rroff2** [comment]
Will definitely check it out - I have a 3070 w/ a HDR1000 display (Philips 436M6).
