### ISSUE TITLE
There are bugs in the Quake 2 RTX console

### ISSUE THREAD

**Issue by maximus105** [NVIDIA/Q2RTX#88]
After starting Quake 2 RTX, the console contains bugs highlighted in red. What do these bugs affect and can they be fixed somehow?

![q2rtx_2020_10_11_11_58_46_148](https://user-images.githubusercontent.com/58270614/95674927-2bb56f00-0bbc-11eb-9485-60659f5bf8b6.png)

**Comment by byte1024** [comment]
They might not affect anything. Errors in the log may not cause any issues and might just be there for reference.

The important thing for you is if the game works fine.

**Comment by apanteleev** [comment]
Right - these are not "bugs", they are warning messages about some Vulkan functions being unavailable on the current machine / game build. For example, the vkDebugMarker... function is only available when the debug layer is enabled, and it's not enabled in public builds.
Closing.
