### ISSUE TITLE
 Quake II RTX Crash

### ISSUE THREAD

**Issue by jogakdal** [NVIDIA/Q2RTX#89]
I get an unhandled exception error when running Quake II RTX.
CPU: RYZEN 5800X
VIDEO: ZOTAC GAMING GeForce RTX 3070 Edge OC D6 8GB TWIN HDMI connection

crash report:
Crash report generated Nov 28 2020, 06:02:35 UTC
by q2rtx 1.3.0-711e686, built Dec 20 2019, 14:49:01

Windows version: 6.2 (build 9200) 

Loaded modules:
0x00007ff6d2810000 0x00007ff6d38de000 q2rtx (version 1.3.0.0, symbols PDB)
0x00007ff9df690000 0x00007ff9df886000 ntdll (version 6.2.19041.610, symbols export)
0x00007ff9ddad0000 0x00007ff9ddb8d000 KERNEL32 (version 6.2.19041.546, symbols export)
0x00007ff9dd2e0000 0x00007ff9dd5a8000 KERNELBASE (version 6.2.19041.572, symbols export)
0x00007ff9ded90000 0x00007ff9dedfb000 WS2_32 (version 6.2.19041.546, symbols export)
0x00007ff9ddcb0000 0x00007ff9dddd4000 RPCRT4 (version 6.2.19041.630, symbols export)
0x00007ff9de200000 0x00007ff9de3a0000 USER32 (version 6.2.19041.610, symbols export)
0x00007ff9d4df0000 0x00007ff9d4e17000 WINMM (version 6.2.19041.546, symbols export)
0x00007ff9dd0f0000 0x00007ff9dd112000 win32u (version 6.2.19041.630, symbols export)
0x00007ff9de640000 0x00007ff9de6de000 msvcrt (version 7.0.19041.546, symbols export)
0x00007ff9ca8a0000 0x00007ff9ca9a5000 vulkan-1 (version 1.2.141.0, symbols export)
0x00007ff9ddfc0000 0x00007ff9ddfea000 GDI32 (version 6.2.19041.546, symbols export)
0x00007ff9dd5b0000 0x00007ff9dd6b9000 gdi32full (version 6.2.19041.572, symbols export)
0x00007ff9dcdd0000 0x00007ff9dce6d000 msvcp_win (version 6.2.19041.546, symbols export)
0x00007ff9dcff0000 0x00007ff9dd0f0000 ucrtbase (version 6.2.19041.546, symbols export)
0x00007ff9dce70000 0x00007ff9dcebe000 CFGMGR32 (version 6.2.19041.546, symbols export)
0x00007ff9df600000 0x00007ff9df630000 IMM32 (version 6.2.19041.546, symbols export)
0x00007ff9ddde0000 0x00007ff9ddf0a000 ole32 (version 6.2.19041.546, symbols export)
0x00007ff9ddf10000 0x00007ff9ddfbc000 ADVAPI32 (version 6.2.19041.610, symbols export)
0x00007ff9de7c0000 0x00007ff9de85b000 sechost (version 6.2.19041.546, symbols export)
0x00007ff9dd770000 0x00007ff9ddac5000 combase (version 6.2.19041.572, symbols export)
0x00007ff9de0c0000 0x00007ff9de18d000 OLEAUT32 (version 6.2.19041.546, symbols export)
0x00007ff9de860000 0x00007ff9decc7000 SETUPAPI (version 6.2.19041.546, symbols export)
0x00007ff9dd6c0000 0x00007ff9dd6e7000 bcrypt (version 6.2.19041.546, symbols export)
0x00007ff9dee00000 0x00007ff9df541000 SHELL32 (version 6.2.19041.610, symbols export)
0x00007ff9d6e80000 0x00007ff9d6e8a000 VERSION (version 6.2.19041.546, symbols export)
0x00007ff9dc560000 0x00007ff9dc5ca000 mswsock (version 6.2.19041.546, symbols export)
0x00007ff9da7a0000 0x00007ff9da83e000 uxtheme (version 6.2.19041.610, symbols export)
0x00007ff9df550000 0x00007ff9df5fe000 SHCORE (version 6.2.19041.610, symbols export)
0x00007ff9db6e0000 0x00007ff9db7d3000 dxgi (version 6.2.19041.546, symbols export)
0x00007ff9dad00000 0x00007ff9dad12000 kernel.appcore (version 6.2.19041.546, symbols export)
0x00007ff993a20000 0x00007ff996700000 nvoglv64 (version 27.21.14.5730, symbols export) *
0x00007ff9d8550000 0x00007ff9d8564000 WTSAPI32 (version 6.2.19041.546, symbols export)
0x00007ff9dc9c0000 0x00007ff9dc9d2000 msasn1 (version 6.2.19041.546, symbols export)
0x00007ff9d6e40000 0x00007ff9d6e71000 cryptnet (version 6.2.19041.546, symbols export)
0x00007ff9dd120000 0x00007ff9dd27d000 CRYPT32 (version 6.2.19041.546, symbols export)
0x00007ff9dc6e0000 0x00007ff9dc6ec000 cryptbase (version 6.2.19041.546, symbols export)
0x00007ff9dcb80000 0x00007ff9dcbac000 DEVOBJ (version 6.2.19041.546, symbols export)
0x00007ff9dd280000 0x00007ff9dd2e0000 WINTRUST (version 6.2.19041.630, symbols export)
0x00007ff9dbad0000 0x00007ff9dbb03000 ntmarta (version 6.2.19041.546, symbols export)
0x00007ff9ddb90000 0x00007ff9ddca5000 MSCTF (version 6.2.19041.630, symbols export)
0x00007ff9dcec0000 0x00007ff9dcf3f000 bcryptPrimitives (version 6.2.19041.546, symbols export)
0x00007ff9decd0000 0x00007ff9ded79000 clbcatq (version 2001.12.10941.16384, symbols export)
0x00007ff9d6d30000 0x00007ff9d6e27000 PROPSYS (version 7.0.19041.546, symbols export)
0x00007ff9b2340000 0x00007ff9b243c000 textinputframework (version 6.2.19041.610, symbols export)
0x00007ff9da0e0000 0x00007ff9da43e000 CoreUIComponents (version 6.2.19041.546, symbols export)
0x00007ff9da440000 0x00007ff9da532000 CoreMessaging (version 6.2.19041.610, symbols export)
0x00007ff9d8d80000 0x00007ff9d8ed6000 wintypes (version 6.2.19041.572, symbols export)
0x00007ff9ddff0000 0x00007ff9de045000 SHLWAPI (version 6.2.19041.546, symbols export)
0x00007ff9c3280000 0x00007ff9c32c0000 imkrapi (version 6.2.19041.329, symbols export)
0x00007ff9d7ff0000 0x00007ff9d8090000 policymanager (version 6.2.19041.610, symbols export)
0x00007ff9dbf40000 0x00007ff9dbfca000 msvcp110_win (version 6.2.19041.546, symbols export)
0x00007ff9c1fd0000 0x00007ff9c200e000 imjkapi (version 6.2.19041.329, symbols export)
0x00007ff9d4d90000 0x00007ff9d4dcb000 dxcore (version 6.2.19041.546, symbols export)
0x00007ff9daf00000 0x00007ff9db695000 windows.storage (version 6.2.19041.610, symbols export)
0x00007ff9dc770000 0x00007ff9dc79c000 Wldp (version 6.2.19041.546, symbols export)
0x00007ff9968f0000 0x00007ff996ba9000 nvspcap64 (version 3.20.5.70, symbols export)
0x00007ff9dcd00000 0x00007ff9dcd26000 profapi (version 6.2.19041.546, symbols none)
0x00007ff9daa10000 0x00007ff9daa3f000 dwmapi (version 6.2.19041.546, symbols export)
0x00007ff9df630000 0x00007ff9df64d000 imagehlp (version 6.2.19041.546, symbols export)
0x00007ff9dc7b0000 0x00007ff9dc7c8000 CRYPTSP (version 6.2.19041.546, symbols export)
0x00007ff9dbea0000 0x00007ff9dbed4000 rsaenh (version 6.2.19041.546, symbols export)
0x00007ff9db6b0000 0x00007ff9db6d3000 gpapi (version 6.2.19041.572, symbols export)
0x00007ff9cd1a0000 0x00007ff9cd24c000 NvCameraAllowlisting64 (version 7.0.636.659, symbols export)
0x00007ff993280000 0x00007ff993a1b000 NvCamera64 (version 7.0.636.659, symbols export)
0x00007ff9c2f50000 0x00007ff9c3104000 WindowsCodecs (version 6.2.19041.546, symbols export)
0x00007ff9d8140000 0x00007ff9d8147000 XINPUT9_1_0 (version 6.2.19041.1, symbols export)
0x00007ff9d5900000 0x00007ff9d5945000 DINPUT8 (version 6.2.19041.1, symbols export)
0x00007ff9db6a0000 0x00007ff9db6ad000 HID (version 6.2.19041.546, symbols export)
0x00007ff9d9340000 0x00007ff9d95a4000 d3d11 (version 6.2.19041.546, symbols export)
0x00007ff9b3280000 0x00007ff9b33d2000 inputhost (version 6.2.19041.546, symbols export)
0x00007ff98abd0000 0x00007ff98afd4000 d3dcompiler_47_64 (version 6.3.9600.16384, symbols export)
0x00007ff9c1940000 0x00007ff9c1a42000 nvldumdx (version 27.21.14.5730, symbols export)
0x00007ff990570000 0x00007ff993030000 nvwgf2umx (version 27.21.14.5730, symbols export)
0x00007ff9c4330000 0x00007ff9c4a06000 nvapi64 (version 27.21.14.5730, symbols export)
0x00007ff9706a0000 0x00007ff971bcc000 nvcuda64 (version 27.21.14.5730, symbols export)
0x00007ff96d3e0000 0x00007ff970696000 nvrtum64 (version 27.21.14.5730, symbols export)
0x00007ff9ca770000 0x00007ff9ca895000 opengl32 (version 6.2.19041.546, symbols export)
0x00007ff9d5af0000 0x00007ff9d5b1c000 GLU32 (version 6.2.19041.546, symbols export)
0x00007ff9dc340000 0x00007ff9dc38b000 powrprof (version 6.2.19041.546, symbols export)
0x00007ff9dc200000 0x00007ff9dc212000 UMPDC (version unknown, symbols export)
0x00007ff9dbb40000 0x00007ff9dbb9a000 WINSTA (version 6.2.19041.546, symbols export)
0x00007ff98a300000 0x00007ff98abc3000 nvptxJitCompiler64 (version 27.21.14.5730, symbols export)
0x00007ff9b6220000 0x00007ff9b62cc000 TextShaping (version unknown, symbols export)
0x00007ff9cf780000 0x00007ff9cfa1b000 comctl32 (version 6.10.19041.488, symbols export)
0x00007ff9d4590000 0x00007ff9d4774000 dbghelp (version 6.2.19041.488, symbols export)

Exception information:
Code: 0xc0000005
Address: 0x00007ff994a52d2f (nvoglv64)

Thread context:
RIP: 0x00007ff994a52d2f RBP: 0x000000f0ae8ff3d0 RSP: 0x000000f0ae8ff0f0
RAX: 0x000002972b6dd020 RBX: 0x0000000000000000 RCX: 0x0000000000000000
RDX: 0x000000f0ae8ff3d0 RSI: 0x000002977d305ee0 RDI: 0x000002977d30e1f0
R8 : 0x00007ff995c0e9c0 R9 : 0x0000000000000040 R10: 0x0000000000000080
R11: 0x000000f0ae8fef30 R12: 0x0000000000000002 R13: 0x0000000000000000
R14: 0x0000000000000000 R15: 0x0000000000000000

Stack trace:
0: 0x000000f0ae8ff303 0x00007ff9ffffff03 0x0000029700000002 0x00007ff9ffffffff nvoglv64!0x00007ff994a52d2f
1: 0x0000000000000001 0x0000000000000000 0x000000f0ae8ff350 0x0000000000000002 nvoglv64!0x00007ff994a45369
2: 0x0000000000000012 0x0000000000000000 0x00007ff6d2b85258 0x0000000000000000 q2rtx!UploadImage+0x0000029b
3: 0x0000000000000000 0x00007ff900000086 0x00007ff6d363cb20 0x0000000000000008 q2rtx!LoadImageFromDDS+0x00000221
4: 0x0000000000000000 0x0000000000000000 0x0000000000000012 0x0000000000000000 q2rtx!SkyInitializeDataGPU+0x00000036
5: 0x00007ff6d2cc27fc 0x0000000000000008 0x00007ff6d2cc26fc 0x0000000000000000 q2rtx!vkpt_physical_sky_initialize+0x0000002d
6: 0x00007ff6d2cc2cd8 0x0000000000000000 0x0000000000000000 0x0000000000000000 q2rtx!vkpt_initialize_all+0x00000079
7: 0x0000029719ba5690 0x0000000000000000 0x00007ff6d2f12fb0 0x0000000000000000 q2rtx!R_Init_RTX+0x00000ebd
8: 0x0000029719ba5690 0x0000000000000008 0x0000000000000000 0x00007ff6d2f12fb0 q2rtx!CL_InitRefresh+0x00000184
9: 0x0000029719ba5690 0x0000029719ba5690 0x0000000000000000 0x000000f0ae8ff450 q2rtx!CL_Init+0x00000035
10: 0x0000000000000001 0x00007ff6d2f12fb0 0x0000000000000001 0x00007ff6d2b6c7a0 q2rtx!Qcommon_Init+0x000006a5
11: 0x0000000000000001 0x0000000000000000 0x0000000000000000 0x0000000000000000 q2rtx!WinMain+0x00000107
12: 0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000 q2rtx!__scrt_common_main_seh+0x00000106
13: 0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000 KERNEL32!0x00007ff9ddae7034
14: 0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000 ntdll!0x00007ff9df6dcec1

**Comment by Squall-Leonhart** [comment]
uninstall twitch studio

**Comment by byte1024** [comment]
> uninstall twitch studio

Curious how you got twitch from that? If its just a guess then it has a fair chance of being incorrect for a one liner =)

**Comment by gelvy** [comment]
To resolve this issue, I ran a search for nvoglv64.dll, deleted the three instances that appeared. I then reinstalled the NVIDIA drivers it failed. I then tried again as Administrator and using the "Perform clean installation" option. Once installed, I rebooted, and the game launched first try. I hope this helps someone.
