### ISSUE TITLE
pt_fake_roughness_threshold

### ISSUE THREAD

**Issue by DU-jdto** [NVIDIA/Q2RTX#9]
pt_fake_roughness_threshold = 1 is the 'reference' value used, and the value at which the fake specular is no longer computed in asvgf_atrous.comp. However, fake_specular_weight = smoothstep(1 - 0.05, 1 + 0.05, roughness) will still be nonzero for roughness > 0.95. In my local fork I've fixed this by replacing the two instances of this computation (one in indirect_lighting.rgen, one in asvgf_atrous.comp) with

```
			float fake_specular_weight = smoothstep(
				global_ubo.pt_fake_roughness_threshold,
				global_ubo.pt_fake_roughness_threshold + 0.1,
				roughness);
```

**Comment by apanteleev** [comment]
Fixed, closing. Thank you.
