### ISSUE TITLE
Quake II RTX is produce unhandled exception each time when I try to start game, any info please?

### ISSUE THREAD

**Issue by g0ldieGun** [NVIDIA/Q2RTX#91]
Crash report generated Dec 6 2020, 21:04:20 UTC
by q2rtx 1.3.0-711e686, built Dec 20 2019, 14:49:01

Windows version: 6.2 (build 9200) 

Loaded modules:
0x00007ff6dca90000 0x00007ff6ddb5e000 q2rtx (version 1.3.0.0, symbols export) *
0x00007ffee6960000 0x00007ffee6b50000 ntdll (version 6.2.18362.1171, symbols export)
0x00007ffee5d70000 0x00007ffee5e22000 KERNEL32 (version 6.2.18362.1110, symbols export)
0x00007ffee42c0000 0x00007ffee4565000 KERNELBASE (version 6.2.18362.1139, symbols export)
0x00007ffee15c0000 0x00007ffee164f000 apphelp (version 6.2.18362.1139, symbols export)
0x00007ffee5ba0000 0x00007ffee5c0f000 WS2_32 (version 6.2.18362.387, symbols export)
0x00007ffee5890000 0x00007ffee59b0000 RPCRT4 (version 6.2.18362.1198, symbols export)
0x00007ffee13c0000 0x00007ffee13e4000 WINMM (version 6.2.18362.1, symbols export)
0x00007ffee4a10000 0x00007ffee4ba4000 USER32 (version 6.2.18362.1171, symbols export)
0x00007ffe8a840000 0x00007ffe8a945000 vulkan-1 (version 1.2.141.0, symbols export)
0x00007ffee61f0000 0x00007ffee628e000 msvcrt (version 7.0.18362.1, symbols export)
0x00007ffee40d0000 0x00007ffee40f1000 win32u (version 6.2.18362.1198, symbols export)
0x00007ffee59b0000 0x00007ffee59d6000 GDI32 (version 6.2.18362.1, symbols export)
0x00007ffee4650000 0x00007ffee47e6000 gdi32full (version 6.2.18362.1139, symbols export)
0x00007ffee1390000 0x00007ffee13bd000 WINMMBASE (version 6.2.18362.1, symbols export)
0x00007ffee4220000 0x00007ffee42be000 msvcp_win (version 6.2.18362.1110, symbols export)
0x00007ffee47f0000 0x00007ffee483a000 cfgmgr32 (version 6.2.18362.387, symbols export)
0x00007ffee4120000 0x00007ffee421a000 ucrtbase (version 6.2.18362.1110, symbols export)
0x00007ffee6610000 0x00007ffee663e000 IMM32 (version 6.2.18362.387, symbols export)
0x00007ffee63b0000 0x00007ffee6453000 ADVAPI32 (version 6.2.18362.752, symbols export)
0x00007ffee59e0000 0x00007ffee5b37000 ole32 (version 6.2.18362.1082, symbols export)
0x00007ffee6640000 0x00007ffee66d7000 sechost (version 6.2.18362.959, symbols export)
0x00007ffee5e30000 0x00007ffee6165000 combase (version 6.2.18362.1171, symbols export)
0x00007ffee4840000 0x00007ffee48c0000 bcryptPrimitives (version 6.2.18362.836, symbols export)
0x00007ffee5c30000 0x00007ffee5cf5000 OLEAUT32 (version 6.2.18362.1110, symbols export)
0x00007ffee52a0000 0x00007ffee5710000 SETUPAPI (version 6.2.18362.1, symbols export)
0x00007ffee4570000 0x00007ffee4596000 bcrypt (version 6.2.18362.267, symbols export)
0x00007ffedd840000 0x00007ffedd84a000 VERSION (version 6.2.18362.1, symbols export)
0x00007ffee4bb0000 0x00007ffee5297000 SHELL32 (version 6.2.18362.1171, symbols export)
0x00007ffee5710000 0x00007ffee57b9000 shcore (version 6.2.18362.1171, symbols export)
0x00007ffee38e0000 0x00007ffee4061000 windows.storage (version 6.2.18362.1171, symbols export)
0x00007ffee38b0000 0x00007ffee38d3000 profapi (version 6.2.18362.693, symbols none)
0x00007ffee3860000 0x00007ffee38aa000 powrprof (version 6.2.18362.1, symbols export)
0x00007ffee3810000 0x00007ffee3820000 UMPDC (version unknown, symbols export)
0x00007ffee5b40000 0x00007ffee5b92000 shlwapi (version 6.2.18362.1, symbols export)
0x00007ffee3820000 0x00007ffee3831000 kernel.appcore (version 6.2.18362.1171, symbols export)
0x00007ffee4100000 0x00007ffee4117000 cryptsp (version 6.2.18362.1, symbols export)
0x00007ffe886c0000 0x00007ffe888a1000 gameoverlayrenderer64 (version 6.17.23.25, symbols export)
0x00007ffee68b0000 0x00007ffee68b8000 PSAPI (version 6.2.18362.1, symbols export)
0x00007ffee2fb0000 0x00007ffee3017000 mswsock (version 6.2.18362.815, symbols export)
0x00007ffee16f0000 0x00007ffee1789000 uxtheme (version 6.2.18362.449, symbols export)
0x00007ffea0e90000 0x00007ffea0fe6000 opengl32 (version 6.2.18362.387, symbols export)
0x00007ffed17f0000 0x00007ffed181c000 GLU32 (version 6.2.18362.387, symbols export)
0x00007ffee2480000 0x00007ffee24a0000 dxcore (version 6.2.18362.1, symbols export)
0x00007ffee6770000 0x00007ffee68a5000 MSCTF (version 6.2.18362.1198, symbols export)
0x00007ffe66270000 0x00007ffe68f50000 nvoglv64 (version 27.21.14.5730, symbols export)
0x00007ffedfe80000 0x00007ffedfe93000 WTSAPI32 (version 6.2.18362.1, symbols export)
0x00007ffee3840000 0x00007ffee3852000 msasn1 (version 6.2.18362.1, symbols export)
0x00007ffedd560000 0x00007ffedd58f000 cryptnet (version 6.2.18362.1, symbols export)
0x00007ffee48c0000 0x00007ffee4a09000 CRYPT32 (version 6.2.18362.592, symbols export)
0x00007ffee3130000 0x00007ffee313c000 cryptbase (version 6.2.18362.1, symbols export)
0x00007ffee3600000 0x00007ffee362a000 DEVOBJ (version 6.2.18362.387, symbols export)
0x00000201732f0000 0x000002017334c000 WINTRUST (version 6.2.18362.1198, symbols export)
0x00007ffee2810000 0x00007ffee2841000 ntmarta (version 6.2.18362.1, symbols export)
0x00007ffec4a30000 0x00007ffec4ce9000 nvspcap64 (version 3.20.5.70, symbols export)
0x00007ffee1c30000 0x00007ffee1c5d000 dwmapi (version 6.2.18362.267, symbols export)
0x00007ffee31a0000 0x00007ffee31f6000 WINSTA (version 6.2.18362.836, symbols export)
0x00007ffee6300000 0x00007ffee63a2000 clbcatq (version 2001.12.10941.16384, symbols export)
0x00007ffedb1e0000 0x00007ffedb27e000 TextInputFramework (version 6.2.18362.1171, symbols export)
0x00007ffedf390000 0x00007ffedf6ba000 CoreUIComponents (version 6.2.18362.1110, symbols export)
0x00007ffee0f40000 0x00007ffee1014000 CoreMessaging (version 6.2.18362.1049, symbols export)
0x00007ffedf230000 0x00007ffedf383000 wintypes (version 6.2.18362.1171, symbols export)
0x00007ffed6e70000 0x00007ffed7117000 iertutil (version 11.0.18362.1198, symbols export)
0x0000000010000000 0x0000000010021000 openal32 (version 6.14.357.25, symbols export)
0x00007ffedd000000 0x00007ffedd072000 MMDevAPI (version 6.2.18362.387, symbols export)
0x00007ffeae6e0000 0x00007ffeae724000 wdmaud (version 6.2.18362.1, symbols export)
0x00007ffed7e20000 0x00007ffed7e29000 ksuser (version 6.2.18362.1, symbols export)
0x00007ffedfa70000 0x00007ffedfa7a000 AVRT (version 6.2.18362.1, symbols export)
0x00007ffedd120000 0x00007ffedd27d000 AUDIOSES (version 6.2.18362.1110, symbols export)
0x00007ffed78e0000 0x00007ffed78ed000 msacm32 (version 6.2.18362.1, symbols export)
0x00007ffed78c0000 0x00007ffed78dc000 MSACM32 (version 6.2.18362.1, symbols export)
0x00007ffed6ce0000 0x00007ffed6cea000 midimap (version 6.2.18362.1, symbols export)
0x00007ffe8a950000 0x00007ffe8a9e9000 dsound (version 6.2.18362.1, symbols export)
0x00007ffee1a20000 0x00007ffee1a34000 resourcepolicyclient (version 6.2.18362.959, symbols export)
0x00000000002c0000 0x0000000000743000 wrap_oal (version 2.2.0.7, symbols export)
0x00007ffedb280000 0x00007ffedb3d1000 Windows.UI (version 6.2.18362.1171, symbols export)
0x00007ffedb0c0000 0x00007ffedb1db000 InputHost (version 6.2.18362.959, symbols export)
0x00007ffedfd30000 0x00007ffedfe20000 PROPSYS (version 7.0.18362.815, symbols export)
0x00007ffee2d10000 0x00007ffee2ddb000 DNSAPI (version 6.2.18362.1171, symbols export)
0x00007ffee6760000 0x00007ffee6768000 NSI (version 6.2.18362.1171, symbols export)
0x00007ffee2cd0000 0x00007ffee2d0a000 IPHLPAPI (version 6.2.18362.1, symbols export)
0x00007ffedc110000 0x00007ffedc11a000 rasadhlp (version 6.2.18362.1, symbols export)
0x00007ffedce60000 0x00007ffedced7000 fwpuclnt (version 6.2.18362.1110, symbols export)
0x00007ffed3ed0000 0x00007ffed4154000 comctl32 (version 6.10.18362.1198, symbols export)
0x00007ffece760000 0x00007ffece954000 dbghelp (version 6.2.18362.1049, symbols export)

Exception information:
Code: 0xc0000005
Address: 0x00007ff6dcaca07b (q2rtx)

Thread context:
RIP: 0x00007ff6dcaca07b RBP: 0x00000066a38ff500 RSP: 0x00000066a38ff400
RAX: 0x0000000000000000 RBX: 0x00000000ff00ff00 RCX: 0x0000000000000002
RDX: 0x00007ff6dd151170 RSI: 0x0000000000000092 RDI: 0x00000000000000d8
R8 : 0x000000000000432f R9 : 0x0000020171e97240 R10: 0x00007f9039b52cd0
R11: 0x00000066a38ff4f0 R12: 0x0000000000000000 R13: 0x0000000000000000
R14: 0x00007ff6dd6c98cc R15: 0x00007ff6dca90000

Stack trace:
0: 0x00007ff6dd6c98cc 0x00007ff6dcbb17ee 0x00007ff6dd6c98cc 0x00000000000006e8 q2rtx!0x00007ff6dcaca07b
1: 0x00000000000006e8 0x00000000000000d8 0x0000000000000008 0x0000000000000000 q2rtx!0x00007ff6dcac8d30
2: 0x00000000000006e8 0x00007ff6dcbabec0 0x00000000000006e8 0x0000000000000000 q2rtx!0x00007ff6dcbaf705
3: 0x00000000000006e8 0x00007ff6dd188a90 0x0000000000000000 0x0000000000000000 q2rtx!0x00007ff6dcbabf7a
4: 0x0000000000000001 0x0000000000000000 0x00007ff6dcbabec0 0x00007ff6dd180a10 q2rtx!0x00007ff6dcb14974
5: 0x0000000000000001 0x0000000000000000 0x0000000009b56315 0x0000000000000000 q2rtx!0x00007ff6dcb1467e
6: 0x0000000000000000 0x0000000000000001 0x00007ff6dd192fb0 0x00007ff6dcaf88b6 q2rtx!0x00007ff6dcbac1e0
7: 0x0000000000000001 0x0000000000000000 0x00007ff6dd192fb0 0x0000000000000001 q2rtx!0x00007ff6dcaf7e2b
8: 0x000000000000000a 0x0000000000000000 0x0000000000000000 0x0000020170330000 q2rtx!0x00007ff6dcb42d9c
9: 0x0000000000000000 0x0000000000000000 0x0000000000000000 0x00007ffe886c0000 q2rtx!0x00007ff6dcd41526
10: 0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000 KERNEL32!0x00007ffee5d87c24
11: 0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000 ntdll!0x00007ffee69cd4d1

**Comment by g0ldieGun** [comment]
I found what was produce this exception: It was setting inside the game. If i set railgun effect as core, then exception appears.

**Comment by apanteleev** [comment]
No repro on current `master`, closing.
