### ISSUE TITLE
Crash in monster_use due to null activator

### ISSUE THREAD

**Issue by Rroff2** [NVIDIA/Q2RTX#92]
In specific circumstances the monster_use function can be called with a null activator resulting in a crash (EDIT: This seems largely due to the use of the notarget command - but possibly can happen under other circumstances)

One cause can be a door coming down on top of a monster as shown here: https://www.youtube.com/watch?v=fvQ7dnSEOvI

I believe it can be avoided by simply adding

if (!activator)
return;

But have not tested it extensively.

(In the video I dropped into the level using \map "waste1$power2" and activating god mode and notarget so as to aggro a specific monster to demonstrate - I've not tested to see if it is related at all to notarget)

**Comment by Rroff2** [comment]
Further testing seems to indicate this is generally related to the use of notarget mode.

**Comment by res2k** [comment]
@apanteleev Is it right this was closed? The cited commit doesn't appear to be related to the issue.
(But the commit message contains an issue number, probably for q2pro.)

**Comment by apanteleev** [comment]
No, this is GitHub thinking it's smart. Reopening.

**Comment by apanteleev** [comment]
Fixed in https://github.com/NVIDIA/Q2RTX/commit/9ea8b5fc7c8cd8c47f30da1438f23de4b8fa45a4, closing. Thanks!
