### ISSUE TITLE
Where is the built-in benchmark?

### ISSUE THREAD

**Issue by silentdragoon** [NVIDIA/Q2RTX#94]
Hullo! The press for the latest Q2RTX update suggests that there is a built-in benchmark of some kind, but I don't see a demo file or a menu option for this, and there's no documentation in the read-me. I could have missed it somewhere, so if anyone knows how to activate this please enlighten me! :)

**Comment by aaronp24** [comment]
The Quake engine has console commands to run demos. If you want to run a complete timedemo from the command line, you can do that with this:
```
./q2rtx +s_enable 0 +timedemo 1 +set nextserver quit +demo <demoname>
```
Or you can bring down the console with `~` and then run `timedemo 1` and `demo <whatever>` from there.

**Comment by silentdragoon** [comment]
Ah, I was under the impression that there was a new feature for this based
on some of the coverage, but obviously that's not the case. Thanks for
replying with the necessary console commands, I appreciate it.
