### ISSUE TITLE
1.4.0 Failing to compile on Linux, 1.3.0 Ok.

### ISSUE THREAD

**Issue by jrugia** [NVIDIA/Q2RTX#97]
Trying to compile 1.4.0 is failing halfway. I've taken a look at the makefile in the build folder to try and pin point the issue. Ran "make 'target'" 1by1 and it's failing at 'shaders' and 'client' components (apparently the 2 are failing at the same part).

Compiling the 1.3.0 source code in the same exact environment goes smooth and without any issues.

Build environment is:

OS: Debian 9 (9.13 Updated).
Dependancies/Tools used: Glslang 10.11.0 + SPIRV-Headers 1.5.4(raytracing fixed) + SPIRV-Tools 2020.6

Q2RTX external libraries compiled with SDL 2.0.12 + Vulkan Headers 1.2.165 + other components from github.

![Screenshot at 2020-12-16 19-08-00](https://user-images.githubusercontent.com/13750621/102388942-bd819400-3fd2-11eb-942b-7d7b4bb70d06.png)

![Screenshot at 2020-12-16 19-08-22](https://user-images.githubusercontent.com/13750621/102388952-c07c8480-3fd2-11eb-8e5c-fb5dac0564d2.png)

The 'ignoreIntersectionEXT': undeclared identifier seems to be the culprit. but it's beyond my level of understanding.

Would appreciate any help.

Thanks.

**Comment by aaronp24** [comment]
I think you need a newer build of glslangValidator that has support for the new Vulkan ray tracing extension.

**Comment by jrugia** [comment]
@aaronp24  I could have sworn I saw glslang 10.11 released somewhere in December, but looking at it again shows 27th October which is behind the RT stuff.

Thanks for the headsup Aaron, I'd have probably kept going in circles. :)

**Comment by jrugia** [comment]
That solved the issue, game compiled successfully :+1: 

Closing ticket.
